#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
#  ECLIPSE VPN — Установщик v3.0
#  Один файл. Запуск: sudo bash install.sh
# ═══════════════════════════════════════════════════════════════════════
set -uo pipefail

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'
C='\033[0;36m'; B='\033[1m'; DIM='\033[2m'; NC='\033[0m'

INSTALL_DIR="/opt/eclipse"
LOG="/tmp/eclipse_install.log"
ERRORS=()
STEP=0
> "$LOG"

step() {
  STEP=$((STEP+1))
  echo ""
  echo -e "${B}${C}╔═══════════════════════════════════════════════════╗${NC}"
  printf  "${B}${C}║  ШАГ %d: %-43s║\n${NC}" "$STEP" "$*"
  echo -e "${B}${C}╚═══════════════════════════════════════════════════╝${NC}"
}
ok()   { echo -e "  ${G}✔${NC}  $*"; }
inf()  { echo -e "  ${C}→${NC}  $*"; }
warn() { echo -e "  ${Y}⚠${NC}  $*"; ERRORS+=("$*"); }
die()  {
  echo ""
  echo -e "${R}${B}╔═══════════════════════════════════════════════════╗${NC}"
  echo -e "${R}${B}║  ОШИБКА — УСТАНОВКА ПРЕРВАНА                      ║${NC}"
  echo -e "${R}${B}╚═══════════════════════════════════════════════════╝${NC}"
  echo -e "  ${R}$*${NC}"
  echo -e "\n  ${DIM}Лог: ${LOG}${NC}"
  tail -30 "$LOG" 2>/dev/null | sed 's/^/    /'
  exit 1
}

run_spin() {
  local msg="$1"; shift
  local spins='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' i=0
  "$@" >>"$LOG" 2>&1 &
  local pid=$!
  tput civis 2>/dev/null || true
  while kill -0 "$pid" 2>/dev/null; do
    printf "\r  ${C}${spins:$((i%${#spins})):1}${NC}  ${DIM}%-55s${NC}" "$msg…"
    i=$((i+1)); sleep 0.1
  done
  tput cnorm 2>/dev/null || true
  if wait "$pid"; then
    printf "\r  ${G}✔${NC}  %-55s\n" "$msg"
  else
    printf "\r  ${R}✗${NC}  %-55s\n" "$msg"
    tail -25 "$LOG" | sed 's/^/      /'
    die "Не удалось: $msg"
  fi
}

echo -e "${C}${B}"
cat << 'BANNER'

  ███████╗ ██████╗██╗     ██╗██████╗ ███████╗███████╗
  ██╔════╝██╔════╝██║     ██║██╔══██╗██╔════╝██╔════╝
  █████╗  ██║     ██║     ██║██████╔╝███████╗█████╗
  ██╔══╝  ██║     ██║     ██║██╔═══╝ ╚════██║██╔══╝
  ███████╗╚██████╗███████╗██║██║     ███████║███████╗
  ╚══════╝ ╚═════╝╚══════╝╚═╝╚═╝     ╚══════╝╚══════╝
           INSTALLER v3.0

BANNER
echo -e "${NC}"

# ══════════════════════════════════════════════════════════════════════
step "ОЧИСТКА ПРЕДЫДУЩЕЙ УСТАНОВКИ"

inf "Останавливаем старые контейнеры…"
for dir in /opt/eclipse /opt/eclips; do
  if [[ -f "${dir}/docker-compose.yml" ]]; then
    inf "Стек в ${dir} — останавливаем…"
    (cd "${dir}" && docker compose down --remove-orphans 2>/dev/null) || true
    ok "Остановлен: ${dir}"
  fi
done
for c in eclipse_xray eclipse_backend eclipse_nginx eclips_xray eclips_backend eclips_nginx; do
  docker rm -f "$c" >>$LOG 2>&1 || true
done
for dir in /opt/eclipse /opt/eclips; do
  [[ -d "$dir" ]] && { rm -rf "$dir"; ok "Удалена: $dir"; }
done
ok "Очистка завершена"

# ══════════════════════════════════════════════════════════════════════
step "ПРОВЕРКА СИСТЕМЫ"

[[ $EUID -ne 0 ]] && die "Запустите от root:  sudo bash install.sh"
source /etc/os-release 2>/dev/null || true
ok "ОС: ${PRETTY_NAME:-Unknown}"
ok "Архитектура: $(uname -m)"
ok "Лог: ${LOG}"

# ══════════════════════════════════════════════════════════════════════
step "ВВОД ПАРАМЕТРОВ"

inf "Определяем внешний IP…"
SERVER_IP=""
for url in "https://api.ipify.org" "https://ifconfig.me" "https://icanhazip.com"; do
  _ip=$(curl -s --max-time 5 "$url" 2>/dev/null | tr -d '[:space:]') || true
  [[ "$_ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && { SERVER_IP="$_ip"; break; }
done
[[ -z "$SERVER_IP" ]] && SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}') || true
[[ -z "$SERVER_IP" ]] && SERVER_IP="0.0.0.0"
ok "IP: ${B}${SERVER_IP}${NC}"

echo ""
echo -ne "  ${C}?${NC}  Введите IP или домен сервера [${SERVER_IP}]: "
read -r _inp
SERVER_IP="${_inp:-$SERVER_IP}"
ok "Используем: ${B}${SERVER_IP}${NC}"

echo ""
while true; do
  echo -ne "  ${C}?${NC}  Пароль для веб-интерфейса (мин. 8 символов): "
  read -rs PASS1; echo ""
  if [[ ${#PASS1} -lt 8 ]]; then
    echo -e "  ${R}✗  Минимум 8 символов${NC}"; continue
  fi
  echo -ne "  ${C}?${NC}  Повторите пароль: "
  read -rs PASS2; echo ""
  [[ "$PASS1" == "$PASS2" ]] && { ECLIPSE_UI_PASS="$PASS1"; ok "Пароль принят"; break; }
  echo -e "  ${R}✗  Не совпадают${NC}"
done

# ══════════════════════════════════════════════════════════════════════
step "УСТАНОВКА ПАКЕТОВ"

run_spin "Обновление apt" apt-get update -qq
run_spin "Базовые пакеты" apt-get install -y -qq   curl wget git unzip ufw ca-certificates gnupg lsb-release software-properties-common

# ══════════════════════════════════════════════════════════════════════
step "УСТАНОВКА DOCKER"

if command -v docker &>/dev/null; then
  ok "Docker: $(docker --version | awk '{print $3}' | tr -d ',')"
else
  run_spin "GPG-ключ Docker" bash -c '
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg       | gpg --dearmor -o /etc/apt/keyrings/docker.gpg 2>/dev/null
    chmod a+r /etc/apt/keyrings/docker.gpg'
  run_spin "Репозиторий Docker" bash -c '
    source /etc/os-release
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg]       https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable"       > /etc/apt/sources.list.d/docker.list
    apt-get update -qq'
  run_spin "Docker CE + Compose"     apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker >>$LOG 2>&1 || true
  systemctl start  docker >>$LOG 2>&1 || true
  ok "Docker установлен"
fi
docker compose version >>$LOG 2>&1 || apt-get install -y -qq docker-compose-plugin >>$LOG 2>&1 || true
ok "Docker Compose v2 ✔"

# ══════════════════════════════════════════════════════════════════════
step "ГЕНЕРАЦИЯ X25519 КЛЮЧЕЙ"

XRAY_BIN=""
for c in xray /usr/local/bin/xray /usr/bin/xray; do
  command -v "$c" &>/dev/null && { XRAY_BIN="$c"; break; }
done

if [[ -z "$XRAY_BIN" ]]; then
  ARCH=$(uname -m)
  case "$ARCH" in aarch64|arm64) XA="arm64-v8a";; *) XA="64";; esac
  XVER=$(curl -s --max-time 10 https://api.github.com/repos/XTLS/Xray-core/releases/latest 2>/dev/null     | grep '"tag_name"' | head -1 | sed 's/.*"\([^"]*\)".*/\1/' || echo "v24.9.30")
  [[ "$XVER" =~ ^v[0-9] ]] || XVER="v24.9.30"
  inf "Xray ${XVER} / linux-${XA}"
  run_spin "Скачивание Xray ${XVER}"     wget -q "https://github.com/XTLS/Xray-core/releases/download/${XVER}/Xray-linux-${XA}.zip"     -O /tmp/xray.zip
  run_spin "Распаковка Xray" bash -c '
    unzip -qo /tmp/xray.zip xray -d /usr/local/bin/
    chmod +x /usr/local/bin/xray
    rm -f /tmp/xray.zip'
  XRAY_BIN="/usr/local/bin/xray"
fi
ok "Xray: ${XRAY_BIN}"

echo -n "  ${C}→${NC}  Генерация X25519 ключей… "
KEY_RAW=$("$XRAY_BIN" x25519 2>>$LOG) || die "xray x25519 завершился с ошибкой"
[[ -z "$KEY_RAW" ]] && die "xray x25519 не вернул результат"
echo -e "${G}OK${NC}"
echo "xray x25519: $KEY_RAW" >>$LOG

PRIVATE_KEY=$(echo "$KEY_RAW" | grep -i "private" | grep -oE '[A-Za-z0-9_/+=\-]{40,}' | head -1 || true)
PUBLIC_KEY=$(echo  "$KEY_RAW" | grep -i "public"  | grep -oE '[A-Za-z0-9_/+=\-]{40,}' | head -1 || true)
[[ -z "$PRIVATE_KEY" ]] && PRIVATE_KEY=$(echo "$KEY_RAW" | awk 'NR==1{for(i=NF;i>=1;i--) if(length($i)>20){print $i;exit}}')
[[ -z "$PUBLIC_KEY"  ]] && PUBLIC_KEY=$(echo  "$KEY_RAW" | awk 'NR==2{for(i=NF;i>=1;i--) if(length($i)>20){print $i;exit}}')
[[ -z "$PRIVATE_KEY" || -z "$PUBLIC_KEY" ]] && die "Не удалось распарсить ключи:\n$KEY_RAW"

ok "Private Key: ${B}${PRIVATE_KEY:0:16}…${NC}"
ok "Public Key:  ${B}${PUBLIC_KEY}${NC}"

# ══════════════════════════════════════════════════════════════════════
step "НАСТРОЙКА FIREWALL (UFW)"

ufw --force reset          >>$LOG 2>&1 || true
ufw default deny incoming  >>$LOG 2>&1 || true
ufw default allow outgoing >>$LOG 2>&1 || true
for p in 22 80 443 8080 8443; do
  ufw allow ${p}/tcp >>$LOG 2>&1 || true
  ok "Порт ${p}/tcp — открыт"
done
ufw --force enable >>$LOG 2>&1 || true
ok "UFW включён"

# ══════════════════════════════════════════════════════════════════════
step "СОЗДАНИЕ ФАЙЛОВ ПРОЕКТА"

mkdir -p "${INSTALL_DIR}"/{backend,frontend,nginx,data,xray_config,xray_logs}
inf "Директория: ${INSTALL_DIR}"

decode_file() {
  local b64="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  echo "$b64" | base64 -d > "$dst" 2>>$LOG || die "Не удалось декодировать: $dst"
  ok "Создан: $dst"
}

decode_file "IiIiCkVjbGlwc2UgVlBOIOKAlCBGYXN0QVBJIEJhY2tlbmQKWHJheS1jb3JlIGNvbmZpZyBtYW5hZ2VyLCBEUEkgbW9uaXRvciwga2V5IHJvdGF0aW9uLCBWTEVTUyBsaW5rIGdlbmVyYXRvcgoiIiIKCmltcG9ydCBhc3luY2lvCmltcG9ydCBiYXNlNjQKaW1wb3J0IGhhc2hsaWIKaW1wb3J0IGhtYWMKaW1wb3J0IGpzb24KaW1wb3J0IGxvZ2dpbmcKaW1wb3J0IG9zCmltcG9ydCByYW5kb20KaW1wb3J0IHNlY3JldHMKaW1wb3J0IHN1YnByb2Nlc3MKaW1wb3J0IHRpbWUKaW1wb3J0IHV1aWQKZnJvbSBjb250ZXh0bGliIGltcG9ydCBhc3luY2NvbnRleHRtYW5hZ2VyCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lCmZyb20gaW8gaW1wb3J0IEJ5dGVzSU8KZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmZyb20gdHlwaW5nIGltcG9ydCBPcHRpb25hbAoKaW1wb3J0IGh0dHB4CmltcG9ydCBwc3V0aWwKaW1wb3J0IHFyY29kZQpmcm9tIGFwc2NoZWR1bGVyLnNjaGVkdWxlcnMuYXN5bmNpbyBpbXBvcnQgQXN5bmNJT1NjaGVkdWxlcgpmcm9tIGZhc3RhcGkgaW1wb3J0IERlcGVuZHMsIEZhc3RBUEksIEhUVFBFeGNlcHRpb24sIHN0YXR1cwpmcm9tIGZhc3RhcGkubWlkZGxld2FyZS5jb3JzIGltcG9ydCBDT1JTTWlkZGxld2FyZQpmcm9tIGZhc3RhcGkucmVzcG9uc2VzIGltcG9ydCBTdHJlYW1pbmdSZXNwb25zZQpmcm9tIGZhc3RhcGkuc2VjdXJpdHkgaW1wb3J0IEhUVFBCYXNpYywgSFRUUEJhc2ljQ3JlZGVudGlhbHMKZnJvbSBweWRhbnRpYyBpbXBvcnQgQmFzZU1vZGVsCgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIENvbmZpZyAvIEVudgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAoKbG9nZ2luZy5iYXNpY0NvbmZpZyhsZXZlbD1sb2dnaW5nLklORk8sIGZvcm1hdD0iJShhc2N0aW1lKXMgWyUobGV2ZWxuYW1lKXNdICUobWVzc2FnZSlzIikKbG9nID0gbG9nZ2luZy5nZXRMb2dnZXIoImVjbGlwc2UiKQoKRUNMSVBTRV9QQVNTV09SRCA9IG9zLmdldGVudigiRUNMSVBTRV9QQVNTV09SRCIsICJjaGFuZ2VtZV9zdHJvbmdfcGFzc3dvcmQiKQpYUkFZX0NPTkZJR19QQVRIID0gUGF0aChvcy5nZXRlbnYoIlhSQVlfQ09ORklHX1BBVEgiLCAiL2V0Yy94cmF5L2NvbmZpZy5qc29uIikpClhSQVlfTE9HX1BBVEggICAgPSBQYXRoKG9zLmdldGVudigiWFJBWV9MT0dfUEFUSCIsICAgICIvdmFyL2xvZy94cmF5IikpClNFUlZFUl9JUCAgICAgICAgPSBvcy5nZXRlbnYoIlNFUlZFUl9JUCIsICAiMC4wLjAuMCIpClBSSVZBVEVfS0VZICAgICAgPSBvcy5nZXRlbnYoIlBSSVZBVEVfS0VZIiwgIiIpClBVQkxJQ19LRVkgICAgICAgPSBvcy5nZXRlbnYoIlBVQkxJQ19LRVkiLCAgIiIpCkRBVEFfUEFUSCAgICAgICAgPSBQYXRoKG9zLmdldGVudigiREFUQV9QQVRIIiwgIi9hcHAvZGF0YSIpKQpEQVRBX1BBVEgubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQoKU1RBVEVfRklMRSA9IERBVEFfUEFUSCAvICJzdGF0ZS5qc29uIgoKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBTTkkgcG9vbCDigJQgcm90YXRlZCBldmVyeSAyNGgKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKClNOSV9QT09MID0gWwogICAgImljbG91ZC5jb20iLAogICAgImdhdGV3YXkuaWNsb3VkLmNvbSIsCiAgICAiY2RuLmFwcGxlLWNsb3Vka2l0LmNvbSIsCiAgICAid3d3LmFwcGxlLmNvbSIsCiAgICAiYXBwbGVpZC5hcHBsZS5jb20iLAogICAgImFwaS5zYmVyYmFuay5ydSIsCiAgICAib25saW5lLnNiZXJiYW5rLnJ1IiwKICAgICJnb3N1c2x1Z2kucnUiLAogICAgImxrLmdvc3VzbHVnaS5ydSIsCiAgICAiZXNpYS5nb3N1c2x1Z2kucnUiLApdCgpERVNUX1NJVEVTID0gewogICAgImljbG91ZC5jb20iOiAgICAgICAgIDQ0MywKICAgICJnYXRld2F5LmljbG91ZC5jb20iOiA0NDMsCiAgICAid3d3LmFwcGxlLmNvbSI6ICAgICAgNDQzLAogICAgImdvc3VzbHVnaS5ydSI6ICAgICAgIDQ0MywKfQoKQkxPQ0tFRF9TSVRFU19DSEVDSyA9IFsKICAgICJodHRwczovL3d3dy55b3V0dWJlLmNvbSIsCiAgICAiaHR0cHM6Ly90d2l0dGVyLmNvbSIsCiAgICAiaHR0cHM6Ly9mYWNlYm9vay5jb20iLApdCkRJUkVDVF9TSVRFU19DSEVDSyA9IFsKICAgICJodHRwczovL3d3dy5nb29nbGUuY29tIiwKICAgICJodHRwczovL2Nsb3VkZmxhcmUuY29tIiwKICAgICJodHRwczovLzEuMS4xLjEiLApdCgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIFN0YXRlIGhlbHBlcnMKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCmRlZiBsb2FkX3N0YXRlKCkgLT4gZGljdDoKICAgIGlmIFNUQVRFX0ZJTEUuZXhpc3RzKCk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICByZXR1cm4ganNvbi5sb2FkcyhTVEFURV9GSUxFLnJlYWRfdGV4dCgpKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKICAgIHJldHVybiB7fQoKCmRlZiBzYXZlX3N0YXRlKGRhdGE6IGRpY3QpOgogICAgU1RBVEVfRklMRS53cml0ZV90ZXh0KGpzb24uZHVtcHMoZGF0YSwgaW5kZW50PTIpKQoKCmRlZiBnZW5fc2hvcnRfaWQobGVuZ3RoOiBpbnQgPSA4KSAtPiBzdHI6CiAgICByZXR1cm4gc2VjcmV0cy50b2tlbl9oZXgobGVuZ3RoIC8vIDIpCgoKZGVmIGdlbl91dWlkKCkgLT4gc3RyOgogICAgcmV0dXJuIHN0cih1dWlkLnV1aWQ0KCkpCgoKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBYcmF5IGNvbmZpZyBnZW5lcmF0b3IKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCmRlZiBidWlsZF94cmF5X2NvbmZpZyhzdGF0ZTogZGljdCkgLT4gZGljdDoKICAgIHNuaSAgICAgID0gc3RhdGUuZ2V0KCJzbmkiLCAgICAgIHJhbmRvbS5jaG9pY2UoU05JX1BPT0wpKQogICAgc2hvcnRfaWQgPSBzdGF0ZS5nZXQoInNob3J0X2lkIiwgZ2VuX3Nob3J0X2lkKCkpCiAgICB1c2VyX2lkICA9IHN0YXRlLmdldCgidXNlcl9pZCIsICBnZW5fdXVpZCgpKQogICAgcHJpdl9rZXkgPSBQUklWQVRFX0tFWSBvciBzdGF0ZS5nZXQoInByaXZhdGVfa2V5IiwgIiIpCiAgICBwdWJfa2V5ICA9IFBVQkxJQ19LRVkgIG9yIHN0YXRlLmdldCgicHVibGljX2tleSIsICAiIikKCiAgICBkZXN0X2hvc3QgPSBzbmkKICAgIGRlc3RfcG9ydCA9IERFU1RfU0lURVMuZ2V0KHNuaSwgNDQzKQoKICAgIHJldHVybiB7CiAgICAgICAgImxvZyI6IHsKICAgICAgICAgICAgImxvZ2xldmVsIjogIndhcm5pbmciLAogICAgICAgICAgICAiYWNjZXNzIjogICBzdHIoWFJBWV9MT0dfUEFUSCAvICJhY2Nlc3MubG9nIiksCiAgICAgICAgICAgICJlcnJvciI6ICAgIHN0cihYUkFZX0xPR19QQVRIIC8gImVycm9yLmxvZyIpLAogICAgICAgIH0sCiAgICAgICAgImluYm91bmRzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAibGlzdGVuIjogIjAuMC4wLjAiLAogICAgICAgICAgICAgICAgInBvcnQiOiA0NDMsCiAgICAgICAgICAgICAgICAicHJvdG9jb2wiOiAidmxlc3MiLAogICAgICAgICAgICAgICAgInNldHRpbmdzIjogewogICAgICAgICAgICAgICAgICAgICJjbGllbnRzIjogW3siaWQiOiB1c2VyX2lkLCAiZmxvdyI6ICJ4dGxzLXJwcngtdmlzaW9uIn1dLAogICAgICAgICAgICAgICAgICAgICJkZWNyeXB0aW9uIjogIm5vbmUiLAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJzdHJlYW1TZXR0aW5ncyI6IHsKICAgICAgICAgICAgICAgICAgICAibmV0d29yayI6ICJ0Y3AiLAogICAgICAgICAgICAgICAgICAgICJzZWN1cml0eSI6ICJyZWFsaXR5IiwKICAgICAgICAgICAgICAgICAgICAicmVhbGl0eVNldHRpbmdzIjogewogICAgICAgICAgICAgICAgICAgICAgICAic2hvdyI6IEZhbHNlLAogICAgICAgICAgICAgICAgICAgICAgICAiZGVzdCI6IGYie2Rlc3RfaG9zdH06e2Rlc3RfcG9ydH0iLAogICAgICAgICAgICAgICAgICAgICAgICAieHZlciI6IDAsCiAgICAgICAgICAgICAgICAgICAgICAgICJzZXJ2ZXJOYW1lcyI6IFtzbmldLAogICAgICAgICAgICAgICAgICAgICAgICAicHJpdmF0ZUtleSI6IHByaXZfa2V5LAogICAgICAgICAgICAgICAgICAgICAgICAic2hvcnRJZHMiOiBbc2hvcnRfaWRdLAogICAgICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgInRjcFNldHRpbmdzIjogeyJoZWFkZXIiOiB7InR5cGUiOiAibm9uZSJ9fSwKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAic25pZmZpbmciOiB7CiAgICAgICAgICAgICAgICAgICAgImVuYWJsZWQiOiBUcnVlLAogICAgICAgICAgICAgICAgICAgICJkZXN0T3ZlcnJpZGUiOiBbImh0dHAiLCAidGxzIiwgInF1aWMiXSwKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJsaXN0ZW4iOiAiMC4wLjAuMCIsCiAgICAgICAgICAgICAgICAicG9ydCI6IDg0NDMsCiAgICAgICAgICAgICAgICAicHJvdG9jb2wiOiAidmxlc3MiLAogICAgICAgICAgICAgICAgInNldHRpbmdzIjogewogICAgICAgICAgICAgICAgICAgICJjbGllbnRzIjogW3siaWQiOiB1c2VyX2lkLCAiZmxvdyI6ICIifV0sCiAgICAgICAgICAgICAgICAgICAgImRlY3J5cHRpb24iOiAibm9uZSIsCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgInN0cmVhbVNldHRpbmdzIjogewogICAgICAgICAgICAgICAgICAgICJuZXR3b3JrIjogImdycGMiLAogICAgICAgICAgICAgICAgICAgICJzZWN1cml0eSI6ICJyZWFsaXR5IiwKICAgICAgICAgICAgICAgICAgICAicmVhbGl0eVNldHRpbmdzIjogewogICAgICAgICAgICAgICAgICAgICAgICAic2hvdyI6IEZhbHNlLAogICAgICAgICAgICAgICAgICAgICAgICAiZGVzdCI6IGYie2Rlc3RfaG9zdH06e2Rlc3RfcG9ydH0iLAogICAgICAgICAgICAgICAgICAgICAgICAieHZlciI6IDAsCiAgICAgICAgICAgICAgICAgICAgICAgICJzZXJ2ZXJOYW1lcyI6IFtzbmldLAogICAgICAgICAgICAgICAgICAgICAgICAicHJpdmF0ZUtleSI6IHByaXZfa2V5LAogICAgICAgICAgICAgICAgICAgICAgICAic2hvcnRJZHMiOiBbc2hvcnRfaWRdLAogICAgICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgImdycGNTZXR0aW5ncyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgInNlcnZpY2VOYW1lIjogImVjbGlwc2UtZ3JwYyIsCiAgICAgICAgICAgICAgICAgICAgICAgICJtdWx0aU1vZGUiOiBUcnVlLAogICAgICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgInNuaWZmaW5nIjogewogICAgICAgICAgICAgICAgICAgICJlbmFibGVkIjogVHJ1ZSwKICAgICAgICAgICAgICAgICAgICAiZGVzdE92ZXJyaWRlIjogWyJodHRwIiwgInRscyJdLAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgfSwKICAgICAgICBdLAogICAgICAgICJvdXRib3VuZHMiOiBbCiAgICAgICAgICAgIHsicHJvdG9jb2wiOiAiZnJlZWRvbSIsICAgInRhZyI6ICJkaXJlY3QifSwKICAgICAgICAgICAgeyJwcm90b2NvbCI6ICJibGFja2hvbGUiLCAidGFnIjogImJsb2NrIn0sCiAgICAgICAgXSwKICAgICAgICAicm91dGluZyI6IHsKICAgICAgICAgICAgImRvbWFpblN0cmF0ZWd5IjogIklQSWZOb25NYXRjaCIsCiAgICAgICAgICAgICJydWxlcyI6IFsKICAgICAgICAgICAgICAgIHsidHlwZSI6ICJmaWVsZCIsICJpcCI6IFsiZ2VvaXA6cHJpdmF0ZSJdLCAib3V0Ym91bmRUYWciOiAiYmxvY2sifSwKICAgICAgICAgICAgXSwKICAgICAgICB9LAogICAgICAgICJwb2xpY3kiOiB7CiAgICAgICAgICAgICJsZXZlbHMiOiB7CiAgICAgICAgICAgICAgICAiMCI6IHsKICAgICAgICAgICAgICAgICAgICAiaGFuZHNoYWtlIjogICAgNCwKICAgICAgICAgICAgICAgICAgICAiY29ubklkbGUiOiAgICAgMzAwLAogICAgICAgICAgICAgICAgICAgICJ1cGxpbmtPbmx5IjogICA1LAogICAgICAgICAgICAgICAgICAgICJkb3dubGlua09ubHkiOiAzMCwKICAgICAgICAgICAgICAgICAgICAiYnVmZmVyU2l6ZSI6ICAgNCwKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgInN5c3RlbSI6IHsKICAgICAgICAgICAgICAgICJzdGF0c0luYm91bmRVcGxpbmsiOiAgIFRydWUsCiAgICAgICAgICAgICAgICAic3RhdHNJbmJvdW5kRG93bmxpbmsiOiBUcnVlLAogICAgICAgICAgICB9LAogICAgICAgIH0sCiAgICAgICAgInN0YXRzIjoge30sCiAgICB9CgoKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBSb3RhdGlvbgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAoKZGVmIHJvdGF0ZV9zbmlfYW5kX3Nob3J0X2lkKHN0YXRlOiBkaWN0KSAtPiBkaWN0OgogICAgc3RhdGVbInNuaSJdICAgICAgICA9IHJhbmRvbS5jaG9pY2UoU05JX1BPT0wpCiAgICBzdGF0ZVsic2hvcnRfaWQiXSAgID0gZ2VuX3Nob3J0X2lkKCkKICAgIHN0YXRlWyJyb3RhdGVkX2F0Il0gPSBkYXRldGltZS51dGNub3coKS5pc29mb3JtYXQoKQogICAgcmV0dXJuIHN0YXRlCgoKZGVmIHdyaXRlX3hyYXlfY29uZmlnKGNmZzogZGljdCk6CiAgICBYUkFZX0NPTkZJR19QQVRILnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICB0bXAgPSBYUkFZX0NPTkZJR19QQVRILndpdGhfc3VmZml4KCIudG1wIikKICAgIHRtcC53cml0ZV90ZXh0KGpzb24uZHVtcHMoY2ZnLCBpbmRlbnQ9MikpCiAgICB0bXAucmVuYW1lKFhSQVlfQ09ORklHX1BBVEgpCiAgICBsb2cuaW5mbygiWHJheSBjb25maWcgd3JpdHRlbiDihpIgJXMiLCBYUkFZX0NPTkZJR19QQVRIKQoKCmRlZiByZWxvYWRfeHJheSgpOgogICAgdHJ5OgogICAgICAgIHJlc3VsdCA9IHN1YnByb2Nlc3MucnVuKAogICAgICAgICAgICBbInBraWxsIiwgIi1TSUdVU1IxIiwgInhyYXkiXSwKICAgICAgICAgICAgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGltZW91dD01CiAgICAgICAgKQogICAgICAgIGxvZy5pbmZvKCJYcmF5IHJlbG9hZCBzaWduYWwgc2VudCAocmM9JWQpIiwgcmVzdWx0LnJldHVybmNvZGUpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgbG9nLndhcm5pbmcoIkNvdWxkIG5vdCBzZW5kIHJlbG9hZCBzaWduYWw6ICVzIiwgZSkKCgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIFZMRVNTIGxpbmsgYnVpbGRlcgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAoKZGVmIGJ1aWxkX3ZsZXNzX2xpbmsoc3RhdGU6IGRpY3QsIHRyYW5zcG9ydDogc3RyID0gInRjcCIpIC0+IHN0cjoKICAgIHVpZCAgICAgID0gc3RhdGUuZ2V0KCJ1c2VyX2lkIiwgICIiKQogICAgc25pICAgICAgPSBzdGF0ZS5nZXQoInNuaSIsICAgICAgImljbG91ZC5jb20iKQogICAgcHViX2tleSAgPSBQVUJMSUNfS0VZIG9yIHN0YXRlLmdldCgicHVibGljX2tleSIsICIiKQogICAgc2hvcnRfaWQgPSBzdGF0ZS5nZXQoInNob3J0X2lkIiwgIiIpCgogICAgaWYgdHJhbnNwb3J0ID09ICJ0Y3AiOgogICAgICAgIHBvcnQgICA9IDQ0MwogICAgICAgIHBhcmFtcyA9ICgKICAgICAgICAgICAgZiJ0eXBlPXRjcCZzZWN1cml0eT1yZWFsaXR5IgogICAgICAgICAgICBmIiZwYms9e3B1Yl9rZXl9JmZwPXNhZmFyaSZzbmk9e3NuaX0iCiAgICAgICAgICAgIGYiJnNpZD17c2hvcnRfaWR9JmZsb3c9eHRscy1ycHJ4LXZpc2lvbiIKICAgICAgICApCiAgICBlbHNlOgogICAgICAgIHBvcnQgICA9IDg0NDMKICAgICAgICBwYXJhbXMgPSAoCiAgICAgICAgICAgIGYidHlwZT1ncnBjJnNlY3VyaXR5PXJlYWxpdHkiCiAgICAgICAgICAgIGYiJnBiaz17cHViX2tleX0mZnA9Y2hyb21lJnNuaT17c25pfSIKICAgICAgICAgICAgZiImc2lkPXtzaG9ydF9pZH0mc2VydmljZU5hbWU9ZWNsaXBzZS1ncnBjJm1vZGU9bXVsdGkiCiAgICAgICAgKQoKICAgIHJldHVybiBmInZsZXNzOi8ve3VpZH1Ae1NFUlZFUl9JUH06e3BvcnR9P3twYXJhbXN9I2VjbGlwc2Ute3RyYW5zcG9ydH0iCgoKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBEUEkgTW9uaXRvcgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAoKZHBpX2NhY2hlOiBkaWN0ID0geyJzY29yZSI6IDAsICJ1cGRhdGVkX2F0IjogTm9uZSwgImRldGFpbHMiOiB7fX0KCgphc3luYyBkZWYgbWVhc3VyZV9sYXRlbmN5KHVybDogc3RyLCB0aW1lb3V0OiBmbG9hdCA9IDUuMCkgLT4gT3B0aW9uYWxbZmxvYXRdOgogICAgdHJ5OgogICAgICAgIHN0YXJ0ID0gdGltZS5tb25vdG9uaWMoKQogICAgICAgIGFzeW5jIHdpdGggaHR0cHguQXN5bmNDbGllbnQodGltZW91dD10aW1lb3V0LCBmb2xsb3dfcmVkaXJlY3RzPVRydWUpIGFzIGNsaWVudDoKICAgICAgICAgICAgYXdhaXQgY2xpZW50LmdldCh1cmwpCiAgICAgICAgcmV0dXJuIHJvdW5kKCh0aW1lLm1vbm90b25pYygpIC0gc3RhcnQpICogMTAwMCwgMSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcmV0dXJuIE5vbmUKCgphc3luYyBkZWYgcnVuX2RwaV9tb25pdG9yKCk6CiAgICBibG9ja2VkX2xhdCwgZGlyZWN0X2xhdCA9IFtdLCBbXQoKICAgIGZvciB1cmwgaW4gQkxPQ0tFRF9TSVRFU19DSEVDSzoKICAgICAgICBsYXQgPSBhd2FpdCBtZWFzdXJlX2xhdGVuY3kodXJsKQogICAgICAgIGlmIGxhdDoKICAgICAgICAgICAgYmxvY2tlZF9sYXQuYXBwZW5kKGxhdCkKCiAgICBmb3IgdXJsIGluIERJUkVDVF9TSVRFU19DSEVDSzoKICAgICAgICBsYXQgPSBhd2FpdCBtZWFzdXJlX2xhdGVuY3kodXJsKQogICAgICAgIGlmIGxhdDoKICAgICAgICAgICAgZGlyZWN0X2xhdC5hcHBlbmQobGF0KQoKICAgIGF2Z19ibG9ja2VkID0gc3VtKGJsb2NrZWRfbGF0KSAvIGxlbihibG9ja2VkX2xhdCkgaWYgYmxvY2tlZF9sYXQgZWxzZSA5OTk5CiAgICBhdmdfZGlyZWN0ICA9IHN1bShkaXJlY3RfbGF0KSAgLyBsZW4oZGlyZWN0X2xhdCkgIGlmIGRpcmVjdF9sYXQgIGVsc2UgMQogICAgdGltZW91dHMgICAgPSBsZW4oQkxPQ0tFRF9TSVRFU19DSEVDSykgLSBsZW4oYmxvY2tlZF9sYXQpCgogICAgcmF0aW8gPSBhdmdfYmxvY2tlZCAvIG1heChhdmdfZGlyZWN0LCAxKQogICAgc2NvcmUgPSBtaW4oMTAwLCBtYXgoMCwgaW50KChyYXRpbyAtIDEpICogMjApICsgdGltZW91dHMgKiAyMCkpCgogICAgZHBpX2NhY2hlLnVwZGF0ZSh7CiAgICAgICAgInNjb3JlIjogICAgICBzY29yZSwKICAgICAgICAidXBkYXRlZF9hdCI6IGRhdGV0aW1lLnV0Y25vdygpLmlzb2Zvcm1hdCgpLAogICAgICAgICJkZXRhaWxzIjogewogICAgICAgICAgICAiYXZnX2Jsb2NrZWRfbXMiOiAgIGF2Z19ibG9ja2VkLAogICAgICAgICAgICAiYXZnX2RpcmVjdF9tcyI6ICAgIGF2Z19kaXJlY3QsCiAgICAgICAgICAgICJibG9ja2VkX3RpbWVvdXRzIjogdGltZW91dHMsCiAgICAgICAgICAgICJibG9ja2VkX3NhbXBsZXMiOiAgYmxvY2tlZF9sYXQsCiAgICAgICAgICAgICJkaXJlY3Rfc2FtcGxlcyI6ICAgZGlyZWN0X2xhdCwKICAgICAgICB9CiAgICB9KQogICAgbG9nLmluZm8oIkRQSSBzY29yZTogJWQgIChibG9ja2VkPSUuMGZtcyAgZGlyZWN0PSUuMGZtcykiLCBzY29yZSwgYXZnX2Jsb2NrZWQsIGF2Z19kaXJlY3QpCgoKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBTY2hlZHVsZXIKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCnNjaGVkdWxlciA9IEFzeW5jSU9TY2hlZHVsZXIoKQoKCmFzeW5jIGRlZiBzY2hlZHVsZWRfcm90YXRpb24oKToKICAgIGxvZy5pbmZvKCLij7AgU2NoZWR1bGVkIHJvdGF0aW9uIHRyaWdnZXJlZCIpCiAgICBzdGF0ZSA9IGxvYWRfc3RhdGUoKQogICAgc3RhdGUgPSByb3RhdGVfc25pX2FuZF9zaG9ydF9pZChzdGF0ZSkKICAgIHdyaXRlX3hyYXlfY29uZmlnKGJ1aWxkX3hyYXlfY29uZmlnKHN0YXRlKSkKICAgIHJlbG9hZF94cmF5KCkKICAgIHNhdmVfc3RhdGUoc3RhdGUpCiAgICBsb2cuaW5mbygi4pyFIFJvdGF0aW9uIGRvbmUuIFNOSTogJXMgIFNob3J0SUQ6ICVzIiwgc3RhdGVbInNuaSJdLCBzdGF0ZVsic2hvcnRfaWQiXSkKCgojIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIExpZmVzcGFuCiMg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACgpAYXN5bmNjb250ZXh0bWFuYWdlcgphc3luYyBkZWYgbGlmZXNwYW4oYXBwOiBGYXN0QVBJKToKICAgIHN0YXRlID0gbG9hZF9zdGF0ZSgpCiAgICBpZiBub3Qgc3RhdGUuZ2V0KCJ1c2VyX2lkIik6CiAgICAgICAgc3RhdGVbInVzZXJfaWQiXSAgICAgPSBnZW5fdXVpZCgpCiAgICAgICAgc3RhdGVbInNuaSJdICAgICAgICAgPSByYW5kb20uY2hvaWNlKFNOSV9QT09MKQogICAgICAgIHN0YXRlWyJzaG9ydF9pZCJdICAgID0gZ2VuX3Nob3J0X2lkKCkKICAgICAgICBzdGF0ZVsicHJpdmF0ZV9rZXkiXSA9IFBSSVZBVEVfS0VZCiAgICAgICAgc3RhdGVbInB1YmxpY19rZXkiXSAgPSBQVUJMSUNfS0VZCiAgICAgICAgc3RhdGVbInJvdGF0ZWRfYXQiXSAgPSBkYXRldGltZS51dGNub3coKS5pc29mb3JtYXQoKQogICAgICAgIHNhdmVfc3RhdGUoc3RhdGUpCgogICAgd3JpdGVfeHJheV9jb25maWcoYnVpbGRfeHJheV9jb25maWcoc3RhdGUpKQogICAgcmVsb2FkX3hyYXkoKQoKICAgIHNjaGVkdWxlci5hZGRfam9iKHNjaGVkdWxlZF9yb3RhdGlvbiwgImludGVydmFsIiwgaG91cnM9MjQsICAgaWQ9InJvdGF0aW9uIikKICAgIHNjaGVkdWxlci5hZGRfam9iKHJ1bl9kcGlfbW9uaXRvciwgICAgImludGVydmFsIiwgbWludXRlcz0xMCwgaWQ9ImRwaV9tb25pdG9yIikKICAgIHNjaGVkdWxlci5zdGFydCgpCgogICAgYXN5bmNpby5jcmVhdGVfdGFzayhydW5fZHBpX21vbml0b3IoKSkKICAgIHlpZWxkCiAgICBzY2hlZHVsZXIuc2h1dGRvd24oKQoKCiMg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiMgQXBwCiMg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACgphcHAgPSBGYXN0QVBJKHRpdGxlPSJFY2xpcHNlIFZQTiBBUEkiLCB2ZXJzaW9uPSIyLjAuMCIsIGxpZmVzcGFuPWxpZmVzcGFuKQoKYXBwLmFkZF9taWRkbGV3YXJlKAogICAgQ09SU01pZGRsZXdhcmUsCiAgICBhbGxvd19vcmlnaW5zPVsiKiJdLAogICAgYWxsb3dfY3JlZGVudGlhbHM9VHJ1ZSwKICAgIGFsbG93X21ldGhvZHM9WyIqIl0sCiAgICBhbGxvd19oZWFkZXJzPVsiKiJdLAopCgpzZWN1cml0eSA9IEhUVFBCYXNpYygpCgoKZGVmIHZlcmlmeV9wYXNzd29yZChjcmVkZW50aWFsczogSFRUUEJhc2ljQ3JlZGVudGlhbHMgPSBEZXBlbmRzKHNlY3VyaXR5KSk6CiAgICBjb3JyZWN0ID0gaG1hYy5jb21wYXJlX2RpZ2VzdCgKICAgICAgICBjcmVkZW50aWFscy5wYXNzd29yZC5lbmNvZGUoKSwgRUNMSVBTRV9QQVNTV09SRC5lbmNvZGUoKQogICAgKQogICAgaWYgbm90IChjcmVkZW50aWFscy51c2VybmFtZSA9PSAiZWNsaXBzZSIgYW5kIGNvcnJlY3QpOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oCiAgICAgICAgICAgIHN0YXR1c19jb2RlPXN0YXR1cy5IVFRQXzQwMV9VTkFVVEhPUklaRUQsCiAgICAgICAgICAgIGRldGFpbD0iSW52YWxpZCBjcmVkZW50aWFscyIsCiAgICAgICAgICAgIGhlYWRlcnM9eyJXV1ctQXV0aGVudGljYXRlIjogIkJhc2ljIn0sCiAgICAgICAgKQogICAgcmV0dXJuIGNyZWRlbnRpYWxzLnVzZXJuYW1lCgoKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBSb3V0ZXMKIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCkBhcHAuZ2V0KCIvaGVhbHRoIikKYXN5bmMgZGVmIGhlYWx0aCgpOgogICAgcmV0dXJuIHsic3RhdHVzIjogIm9rIiwgInRzIjogZGF0ZXRpbWUudXRjbm93KCkuaXNvZm9ybWF0KCl9CgoKQGFwcC5nZXQoIi9hcGkvc3RhdHVzIiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHZlcmlmeV9wYXNzd29yZCldKQphc3luYyBkZWYgZ2V0X3N0YXR1cygpOgogICAgc3RhdGUgPSBsb2FkX3N0YXRlKCkKICAgIHVwdGltZSA9IE5vbmUKICAgIHRyeToKICAgICAgICB1cHRpbWUgPSBpbnQodGltZS50aW1lKCkgLSBwc3V0aWwuYm9vdF90aW1lKCkpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBhc3MKICAgIHJldHVybiB7CiAgICAgICAgInNuaSI6ICAgICAgICBzdGF0ZS5nZXQoInNuaSIpLAogICAgICAgICJzaG9ydF9pZCI6ICAgc3RhdGUuZ2V0KCJzaG9ydF9pZCIpLAogICAgICAgICJyb3RhdGVkX2F0Ijogc3RhdGUuZ2V0KCJyb3RhdGVkX2F0IiksCiAgICAgICAgInNlcnZlcl9pcCI6ICBTRVJWRVJfSVAsCiAgICAgICAgInVwdGltZV9zZWMiOiB1cHRpbWUsCiAgICAgICAgImRwaSI6ICAgICAgICBkcGlfY2FjaGUsCiAgICAgICAgInBvcnRzIjogICAgICB7InRjcCI6IDQ0MywgImdycGMiOiA4NDQzfSwKICAgIH0KCgpAYXBwLmdldCgiL2FwaS9saW5rcyIsIGRlcGVuZGVuY2llcz1bRGVwZW5kcyh2ZXJpZnlfcGFzc3dvcmQpXSkKYXN5bmMgZGVmIGdldF9saW5rcygpOgogICAgc3RhdGUgPSBsb2FkX3N0YXRlKCkKICAgIHJldHVybiB7CiAgICAgICAgInRjcCI6ICBidWlsZF92bGVzc19saW5rKHN0YXRlLCAidGNwIiksCiAgICAgICAgImdycGMiOiBidWlsZF92bGVzc19saW5rKHN0YXRlLCAiZ3JwYyIpLAogICAgfQoKCkBhcHAuZ2V0KCIvYXBpL3FyL3t0cmFuc3BvcnR9IiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHZlcmlmeV9wYXNzd29yZCldKQphc3luYyBkZWYgZ2V0X3FyKHRyYW5zcG9ydDogc3RyID0gInRjcCIpOgogICAgaWYgdHJhbnNwb3J0IG5vdCBpbiAoInRjcCIsICJncnBjIik6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig0MDAsICJ0cmFuc3BvcnQgbXVzdCBiZSB0Y3Agb3IgZ3JwYyIpCiAgICBzdGF0ZSA9IGxvYWRfc3RhdGUoKQogICAgbGluayAgPSBidWlsZF92bGVzc19saW5rKHN0YXRlLCB0cmFuc3BvcnQpCiAgICBpbWcgICA9IHFyY29kZS5tYWtlKGxpbmspCiAgICBidWYgICA9IEJ5dGVzSU8oKQogICAgaW1nLnNhdmUoYnVmLCBmb3JtYXQ9IlBORyIpCiAgICBidWYuc2VlaygwKQogICAgcmV0dXJuIFN0cmVhbWluZ1Jlc3BvbnNlKGJ1ZiwgbWVkaWFfdHlwZT0iaW1hZ2UvcG5nIikKCgpAYXBwLnBvc3QoIi9hcGkvcm90YXRlIiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHZlcmlmeV9wYXNzd29yZCldKQphc3luYyBkZWYgZW1lcmdlbmN5X3JvdGF0ZSgpOgogICAgc3RhdGUgPSBsb2FkX3N0YXRlKCkKICAgIHN0YXRlID0gcm90YXRlX3NuaV9hbmRfc2hvcnRfaWQoc3RhdGUpCiAgICB3cml0ZV94cmF5X2NvbmZpZyhidWlsZF94cmF5X2NvbmZpZyhzdGF0ZSkpCiAgICByZWxvYWRfeHJheSgpCiAgICBzYXZlX3N0YXRlKHN0YXRlKQogICAgbG9nLmluZm8oIvCfmqggRW1lcmdlbmN5IHJvdGF0aW9uIHRyaWdnZXJlZCB2aWEgQVBJIikKICAgIHJldHVybiB7CiAgICAgICAgInN1Y2Nlc3MiOiAgICAgIFRydWUsCiAgICAgICAgIm5ld19zbmkiOiAgICAgIHN0YXRlWyJzbmkiXSwKICAgICAgICAibmV3X3Nob3J0X2lkIjogc3RhdGVbInNob3J0X2lkIl0sCiAgICAgICAgInJvdGF0ZWRfYXQiOiAgIHN0YXRlWyJyb3RhdGVkX2F0Il0sCiAgICAgICAgInRjcF9saW5rIjogICAgIGJ1aWxkX3ZsZXNzX2xpbmsoc3RhdGUsICJ0Y3AiKSwKICAgICAgICAiZ3JwY19saW5rIjogICAgYnVpbGRfdmxlc3NfbGluayhzdGF0ZSwgImdycGMiKSwKICAgIH0KCgpAYXBwLmdldCgiL2FwaS9kcGkiLCBkZXBlbmRlbmNpZXM9W0RlcGVuZHModmVyaWZ5X3Bhc3N3b3JkKV0pCmFzeW5jIGRlZiBnZXRfZHBpKCk6CiAgICByZXR1cm4gZHBpX2NhY2hlCgoKQGFwcC5wb3N0KCIvYXBpL2RwaS9yZWZyZXNoIiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHZlcmlmeV9wYXNzd29yZCldKQphc3luYyBkZWYgcmVmcmVzaF9kcGkoKToKICAgIGFzeW5jaW8uY3JlYXRlX3Rhc2socnVuX2RwaV9tb25pdG9yKCkpCiAgICByZXR1cm4geyJtZXNzYWdlIjogIkRQSSBwcm9iZSBzdGFydGVkIn0KCgpAYXBwLmdldCgiL2FwaS9sb2dzIiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHZlcmlmeV9wYXNzd29yZCldKQphc3luYyBkZWYgZ2V0X2xvZ3MobGluZXM6IGludCA9IDEwMCk6CiAgICByZXN1bHQgPSB7fQogICAgZm9yIG5hbWUgaW4gKCJhY2Nlc3MiLCAiZXJyb3IiKToKICAgICAgICBmID0gWFJBWV9MT0dfUEFUSCAvIGYie25hbWV9LmxvZyIKICAgICAgICByZXN1bHRbbmFtZV0gPSBmLnJlYWRfdGV4dChlcnJvcnM9InJlcGxhY2UiKS5zcGxpdGxpbmVzKClbLWxpbmVzOl0gaWYgZi5leGlzdHMoKSBlbHNlIFtdCiAgICByZXR1cm4gcmVzdWx0CgoKQGFwcC5nZXQoIi9hcGkvY29uZmlnIiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHZlcmlmeV9wYXNzd29yZCldKQphc3luYyBkZWYgZ2V0X2NvbmZpZygpOgogICAgc3RhdGUgPSBsb2FkX3N0YXRlKCkKICAgIGNmZyAgID0gYnVpbGRfeHJheV9jb25maWcoc3RhdGUpCiAgICBmb3IgaW5iIGluIGNmZy5nZXQoImluYm91bmRzIiwgW10pOgogICAgICAgIHJzID0gaW5iLmdldCgic3RyZWFtU2V0dGluZ3MiLCB7fSkuZ2V0KCJyZWFsaXR5U2V0dGluZ3MiLCB7fSkKICAgICAgICBpZiAicHJpdmF0ZUtleSIgaW4gcnM6CiAgICAgICAgICAgIHJzWyJwcml2YXRlS2V5Il0gPSAiKioqUkVEQUNURUQqKioiCiAgICByZXR1cm4gY2ZnCg=="  "${INSTALL_DIR}/backend/main.py"
decode_file "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9InJ1Ij4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxpbml0aWFsLXNjYWxlPTEiPgo8dGl0bGU+RUNMSVBTRSDigJQgQ29udHJvbCBOb2RlPC90aXRsZT4KPGxpbmsgcmVsPSJwcmVjb25uZWN0IiBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tIj4KPGxpbmsgaHJlZj0iaHR0cHM6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3MyP2ZhbWlseT1TaGFyZStUZWNoK01vbm8mZmFtaWx5PU9yYml0cm9uOndnaHRANDAwOzcwMDs5MDAmZGlzcGxheT1zd2FwIiByZWw9InN0eWxlc2hlZXQiPgo8c2NyaXB0IHNyYz0iaHR0cHM6Ly9jZG5qcy5jbG91ZGZsYXJlLmNvbS9hamF4L2xpYnMvcXJjb2RlanMvMS4wLjAvcXJjb2RlLm1pbi5qcyI+PC9zY3JpcHQ+CjxzdHlsZT4KICA6cm9vdCB7CiAgICAtLWJnOiAgICAgICMwMzA3MTI7CiAgICAtLXN1cmZhY2U6ICMwYTBmMWU7CiAgICAtLWJvcmRlcjogICMwZjIwNDA7CiAgICAtLWFjY2VudDogICMwMGQ0ZmY7CiAgICAtLWFjY2VudDI6ICM3YjJmZmY7CiAgICAtLWdyZWVuOiAgICMwMGZmODg7CiAgICAtLXJlZDogICAgICNmZjM4NjA7CiAgICAtLXllbGxvdzogICNmZmRkNTc7CiAgICAtLXRleHQ6ICAgICNjOGQ4ZjA7CiAgICAtLWRpbTogICAgICMzYTUwNzA7CiAgICAtLWdsb3c6ICAgIDAgMCAyMHB4IHJnYmEoMCwyMTIsMjU1LC4zNSk7CiAgICAtLWdsb3cyOiAgIDAgMCAzMHB4IHJnYmEoMTIzLDQ3LDI1NSwuNCk7CiAgfQoKICAqLCAqOjpiZWZvcmUsICo6OmFmdGVyIHsgYm94LXNpemluZzogYm9yZGVyLWJveDsgbWFyZ2luOiAwOyBwYWRkaW5nOiAwOyB9CgogIGJvZHkgewogICAgYmFja2dyb3VuZDogdmFyKC0tYmcpOwogICAgY29sb3I6IHZhcigtLXRleHQpOwogICAgZm9udC1mYW1pbHk6ICdTaGFyZSBUZWNoIE1vbm8nLCBtb25vc3BhY2U7CiAgICBtaW4taGVpZ2h0OiAxMDB2aDsKICAgIG92ZXJmbG93LXg6IGhpZGRlbjsKICB9CgogIC8qIOKUgOKUgCBTY2FubGluZXMgb3ZlcmxheSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICBib2R5OjpiZWZvcmUgewogICAgY29udGVudDogJyc7CiAgICBwb3NpdGlvbjogZml4ZWQ7IGluc2V0OiAwOyB6LWluZGV4OiA5OTk7IHBvaW50ZXItZXZlbnRzOiBub25lOwogICAgYmFja2dyb3VuZDogcmVwZWF0aW5nLWxpbmVhci1ncmFkaWVudCgKICAgICAgMGRlZywKICAgICAgdHJhbnNwYXJlbnQsCiAgICAgIHRyYW5zcGFyZW50IDJweCwKICAgICAgcmdiYSgwLDAsMCwuMDgpIDJweCwKICAgICAgcmdiYSgwLDAsMCwuMDgpIDRweAogICAgKTsKICB9CgogIC8qIOKUgOKUgCBHcmlkIGJhY2tncm91bmQg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAICovCiAgYm9keTo6YWZ0ZXIgewogICAgY29udGVudDogJyc7CiAgICBwb3NpdGlvbjogZml4ZWQ7IGluc2V0OiAwOyB6LWluZGV4OiAwOyBwb2ludGVyLWV2ZW50czogbm9uZTsKICAgIGJhY2tncm91bmQtaW1hZ2U6CiAgICAgIGxpbmVhci1ncmFkaWVudChyZ2JhKDAsMjEyLDI1NSwuMDMpIDFweCwgdHJhbnNwYXJlbnQgMXB4KSwKICAgICAgbGluZWFyLWdyYWRpZW50KDkwZGVnLCByZ2JhKDAsMjEyLDI1NSwuMDMpIDFweCwgdHJhbnNwYXJlbnQgMXB4KTsKICAgIGJhY2tncm91bmQtc2l6ZTogNDBweCA0MHB4OwogIH0KCiAgLmNvbnRhaW5lciB7CiAgICBwb3NpdGlvbjogcmVsYXRpdmU7IHotaW5kZXg6IDE7CiAgICBtYXgtd2lkdGg6IDEyODBweDsKICAgIG1hcmdpbjogMCBhdXRvOwogICAgcGFkZGluZzogMCAyNHB4IDQ4cHg7CiAgfQoKICAvKiDilIDilIAgSGVhZGVyIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogIGhlYWRlciB7CiAgICBkaXNwbGF5OiBmbGV4OwogICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjsKICAgIHBhZGRpbmc6IDI0cHggMCAyMHB4OwogICAgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgICBtYXJnaW4tYm90dG9tOiAzMnB4OwogIH0KCiAgLmxvZ28gewogICAgZm9udC1mYW1pbHk6ICdPcmJpdHJvbicsIG1vbm9zcGFjZTsKICAgIGZvbnQtd2VpZ2h0OiA5MDA7CiAgICBmb250LXNpemU6IDI4cHg7CiAgICBsZXR0ZXItc3BhY2luZzogNnB4OwogICAgY29sb3I6IHZhcigtLWFjY2VudCk7CiAgICB0ZXh0LXNoYWRvdzogdmFyKC0tZ2xvdyk7CiAgICBkaXNwbGF5OiBmbGV4OwogICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgIGdhcDogMTJweDsKICB9CgogIC5sb2dvLWRvdCB7CiAgICB3aWR0aDogMTBweDsgaGVpZ2h0OiAxMHB4OwogICAgYm9yZGVyLXJhZGl1czogNTAlOwogICAgYmFja2dyb3VuZDogdmFyKC0tZ3JlZW4pOwogICAgYm94LXNoYWRvdzogMCAwIDEycHggdmFyKC0tZ3JlZW4pOwogICAgYW5pbWF0aW9uOiBwdWxzZSAycyBlYXNlLWluLW91dCBpbmZpbml0ZTsKICB9CgogIEBrZXlmcmFtZXMgcHVsc2UgewogICAgMCUsMTAwJSB7IG9wYWNpdHk6IDE7IHRyYW5zZm9ybTogc2NhbGUoMSk7IH0KICAgIDUwJSAgICAgIHsgb3BhY2l0eTogLjU7IHRyYW5zZm9ybTogc2NhbGUoLjgpOyB9CiAgfQoKICAuaGVhZGVyLW1ldGEgewogICAgZm9udC1zaXplOiAxMXB4OwogICAgY29sb3I6IHZhcigtLWRpbSk7CiAgICB0ZXh0LWFsaWduOiByaWdodDsKICAgIGxpbmUtaGVpZ2h0OiAxLjg7CiAgfQoKICAjc2VydmVyLWlwIHsgY29sb3I6IHZhcigtLWFjY2VudCk7IH0KICAjY2xvY2sgICAgIHsgY29sb3I6IHZhcigtLWdyZWVuKTsgfQoKICAvKiDilIDilIAgQXV0aCBvdmVybGF5IOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogICNhdXRoLW92ZXJsYXkgewogICAgcG9zaXRpb246IGZpeGVkOyBpbnNldDogMDsgei1pbmRleDogMTAwOwogICAgYmFja2dyb3VuZDogcmdiYSgzLDcsMTgsLjk3KTsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgZ2FwOiAyMHB4OwogIH0KCiAgLmF1dGgtYm94IHsKICAgIGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWFjY2VudCk7CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1zdXJmYWNlKTsKICAgIHBhZGRpbmc6IDQwcHg7CiAgICB3aWR0aDogMzYwcHg7CiAgICBib3gtc2hhZG93OiB2YXIoLS1nbG93KTsKICB9CgogIC5hdXRoLXRpdGxlIHsKICAgIGZvbnQtZmFtaWx5OiAnT3JiaXRyb24nLCBtb25vc3BhY2U7CiAgICBmb250LXNpemU6IDE4cHg7CiAgICBjb2xvcjogdmFyKC0tYWNjZW50KTsKICAgIGxldHRlci1zcGFjaW5nOiA0cHg7CiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgICBtYXJnaW4tYm90dG9tOiAyOHB4OwogIH0KCiAgLmF1dGgtYm94IGlucHV0IHsKICAgIHdpZHRoOiAxMDAlOwogICAgYmFja2dyb3VuZDogdmFyKC0tYmcpOwogICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIGNvbG9yOiB2YXIoLS10ZXh0KTsKICAgIGZvbnQtZmFtaWx5OiBpbmhlcml0OwogICAgZm9udC1zaXplOiAxNHB4OwogICAgcGFkZGluZzogMTJweCAxNHB4OwogICAgb3V0bGluZTogbm9uZTsKICAgIHRyYW5zaXRpb246IGJvcmRlci1jb2xvciAuMnM7CiAgfQoKICAuYXV0aC1ib3ggaW5wdXQ6Zm9jdXMgeyBib3JkZXItY29sb3I6IHZhcigtLWFjY2VudCk7IH0KCiAgLmJ0biB7CiAgICB3aWR0aDogMTAwJTsKICAgIG1hcmdpbi10b3A6IDE2cHg7CiAgICBiYWNrZ3JvdW5kOiB0cmFuc3BhcmVudDsKICAgIGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWFjY2VudCk7CiAgICBjb2xvcjogdmFyKC0tYWNjZW50KTsKICAgIGZvbnQtZmFtaWx5OiAnT3JiaXRyb24nLCBtb25vc3BhY2U7CiAgICBmb250LXNpemU6IDEycHg7CiAgICBsZXR0ZXItc3BhY2luZzogM3B4OwogICAgcGFkZGluZzogMTNweDsKICAgIGN1cnNvcjogcG9pbnRlcjsKICAgIHRyYW5zaXRpb246IGFsbCAuMnM7CiAgfQoKICAuYnRuOmhvdmVyIHsKICAgIGJhY2tncm91bmQ6IHZhcigtLWFjY2VudCk7CiAgICBjb2xvcjogdmFyKC0tYmcpOwogICAgYm94LXNoYWRvdzogdmFyKC0tZ2xvdyk7CiAgfQoKICAuYnRuLWRhbmdlciB7CiAgICBib3JkZXItY29sb3I6IHZhcigtLXJlZCk7CiAgICBjb2xvcjogdmFyKC0tcmVkKTsKICB9CgogIC5idG4tZGFuZ2VyOmhvdmVyIHsKICAgIGJhY2tncm91bmQ6IHZhcigtLXJlZCk7CiAgICBjb2xvcjogI2ZmZjsKICAgIGJveC1zaGFkb3c6IDAgMCAyMHB4IHJnYmEoMjU1LDU2LDk2LC40KTsKICB9CgogIC5idG4tb3JiaXQgewogICAgYm9yZGVyLWNvbG9yOiB2YXIoLS1hY2NlbnQyKTsKICAgIGNvbG9yOiB2YXIoLS1hY2NlbnQyKTsKICAgIGZvbnQtc2l6ZTogMTFweDsKICAgIGxldHRlci1zcGFjaW5nOiAycHg7CiAgICBwYWRkaW5nOiAxNnB4OwogICAgcG9zaXRpb246IHJlbGF0aXZlOwogICAgb3ZlcmZsb3c6IGhpZGRlbjsKICB9CgogIC5idG4tb3JiaXQ6aG92ZXIgewogICAgYmFja2dyb3VuZDogdmFyKC0tYWNjZW50Mik7CiAgICBjb2xvcjogI2ZmZjsKICAgIGJveC1zaGFkb3c6IHZhcigtLWdsb3cyKTsKICB9CgogIC5idG4tb3JiaXQubG9hZGluZzo6YWZ0ZXIgewogICAgY29udGVudDogJyc7CiAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICBsZWZ0OiAwOyB0b3A6IDA7IGhlaWdodDogM3B4OyB3aWR0aDogMDsKICAgIGJhY2tncm91bmQ6IHZhcigtLWFjY2VudDIpOwogICAgYW5pbWF0aW9uOiBsb2FkLWJhciAxLjVzIGVhc2UgZm9yd2FyZHM7CiAgfQoKICBAa2V5ZnJhbWVzIGxvYWQtYmFyIHsgdG8geyB3aWR0aDogMTAwJTsgfSB9CgogICNhdXRoLWVycm9yIHsKICAgIGNvbG9yOiB2YXIoLS1yZWQpOwogICAgZm9udC1zaXplOiAxMnB4OwogICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgbWluLWhlaWdodDogMThweDsKICB9CgogIC8qIOKUgOKUgCBHcmlkIGxheW91dCDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAuZGFzaGJvYXJkIHsKICAgIGRpc3BsYXk6IGdyaWQ7CiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCgxMiwgMWZyKTsKICAgIGdhcDogMTZweDsKICB9CgogIC5jYXJkIHsKICAgIGJhY2tncm91bmQ6IHZhcigtLXN1cmZhY2UpOwogICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIHBhZGRpbmc6IDIwcHggMjRweDsKICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsKICAgIHRyYW5zaXRpb246IGJvcmRlci1jb2xvciAuM3M7CiAgfQoKICAuY2FyZDpob3ZlciB7IGJvcmRlci1jb2xvcjogcmdiYSgwLDIxMiwyNTUsLjI1KTsgfQoKICAuY2FyZC1sYWJlbCB7CiAgICBmb250LXNpemU6IDEwcHg7CiAgICBsZXR0ZXItc3BhY2luZzogM3B4OwogICAgY29sb3I6IHZhcigtLWRpbSk7CiAgICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOwogICAgbWFyZ2luLWJvdHRvbTogMTJweDsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgZ2FwOiA4cHg7CiAgfQoKICAuY2FyZC1sYWJlbDo6YmVmb3JlIHsKICAgIGNvbnRlbnQ6ICcnOwogICAgZGlzcGxheTogaW5saW5lLWJsb2NrOwogICAgd2lkdGg6IDIwcHg7IGhlaWdodDogMXB4OwogICAgYmFja2dyb3VuZDogdmFyKC0tYWNjZW50KTsKICAgIG9wYWNpdHk6IC41OwogIH0KCiAgLyog4pSA4pSAIEhlYWx0aCBjYXJkIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogIC5jb2wtNCAgeyBncmlkLWNvbHVtbjogc3BhbiA0OyB9CiAgLmNvbC01ICB7IGdyaWQtY29sdW1uOiBzcGFuIDU7IH0KICAuY29sLTYgIHsgZ3JpZC1jb2x1bW46IHNwYW4gNjsgfQogIC5jb2wtNyAgeyBncmlkLWNvbHVtbjogc3BhbiA3OyB9CiAgLmNvbC04ICB7IGdyaWQtY29sdW1uOiBzcGFuIDg7IH0KICAuY29sLTEyIHsgZ3JpZC1jb2x1bW46IHNwYW4gMTI7IH0KCiAgQG1lZGlhIChtYXgtd2lkdGg6IDkwMHB4KSB7CiAgICAuY29sLTQsLmNvbC01LC5jb2wtNiwuY29sLTcsLmNvbC04IHsgZ3JpZC1jb2x1bW46IHNwYW4gMTI7IH0KICB9CgogIC5oZWFsdGgtcmluZyB7CiAgICB3aWR0aDogMTIwcHg7IGhlaWdodDogMTIwcHg7CiAgICBtYXJnaW46IDAgYXV0byAxNnB4OwogICAgcG9zaXRpb246IHJlbGF0aXZlOwogIH0KCiAgLmhlYWx0aC1yaW5nIHN2ZyB7IHRyYW5zZm9ybTogcm90YXRlKC05MGRlZyk7IH0KCiAgLmhlYWx0aC1yaW5nIC5yaW5nLWJnICB7IGZpbGw6IG5vbmU7IHN0cm9rZTogdmFyKC0tYm9yZGVyKTsgc3Ryb2tlLXdpZHRoOiA4OyB9CiAgLmhlYWx0aC1yaW5nIC5yaW5nLXZhbCB7IGZpbGw6IG5vbmU7IHN0cm9rZTogdmFyKC0tZ3JlZW4pOyAgc3Ryb2tlLXdpZHRoOiA4OwogICAgICAgICAgICAgICAgICAgICAgICAgICBzdHJva2UtbGluZWNhcDogcm91bmQ7CiAgICAgICAgICAgICAgICAgICAgICAgICAgIHN0cm9rZS1kYXNoYXJyYXk6IDI4MzsKICAgICAgICAgICAgICAgICAgICAgICAgICAgc3Ryb2tlLWRhc2hvZmZzZXQ6IDI4MzsKICAgICAgICAgICAgICAgICAgICAgICAgICAgdHJhbnNpdGlvbjogc3Ryb2tlLWRhc2hvZmZzZXQgMXMgZWFzZSwgc3Ryb2tlIC41czsgfQoKICAuaGVhbHRoLWNlbnRlciB7CiAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICBpbnNldDogMDsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogIH0KCiAgLmhlYWx0aC1wY3QgewogICAgZm9udC1mYW1pbHk6ICdPcmJpdHJvbicsIG1vbm9zcGFjZTsKICAgIGZvbnQtc2l6ZTogMjRweDsKICAgIGZvbnQtd2VpZ2h0OiA3MDA7CiAgICBjb2xvcjogdmFyKC0tZ3JlZW4pOwogICAgbGluZS1oZWlnaHQ6IDE7CiAgICB0ZXh0LXNoYWRvdzogMCAwIDEycHggdmFyKC0tZ3JlZW4pOwogIH0KCiAgLmhlYWx0aC1sYWJlbCB7IGZvbnQtc2l6ZTogOXB4OyBjb2xvcjogdmFyKC0tZGltKTsgbGV0dGVyLXNwYWNpbmc6IDJweDsgfQoKICAvKiDilIDilIAgRFBJIEdhdWdlIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogIC5kcGktZ2F1Z2Utd3JhcCB7CiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgfQoKICAuZHBpLWJhci1iZyB7CiAgICBoZWlnaHQ6IDEycHg7CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1ib3JkZXIpOwogICAgYm9yZGVyLXJhZGl1czogMnB4OwogICAgb3ZlcmZsb3c6IGhpZGRlbjsKICAgIG1hcmdpbjogMTZweCAwIDhweDsKICB9CgogIC5kcGktYmFyLWZpbGwgewogICAgaGVpZ2h0OiAxMDAlOwogICAgd2lkdGg6IDAlOwogICAgYmFja2dyb3VuZDogbGluZWFyLWdyYWRpZW50KDkwZGVnLCB2YXIoLS1ncmVlbiksIHZhcigtLXllbGxvdyksIHZhcigtLXJlZCkpOwogICAgYm9yZGVyLXJhZGl1czogMnB4OwogICAgdHJhbnNpdGlvbjogd2lkdGggMXMgZWFzZTsKICB9CgogIC5kcGktc2NvcmUtbnVtIHsKICAgIGZvbnQtZmFtaWx5OiAnT3JiaXRyb24nLCBtb25vc3BhY2U7CiAgICBmb250LXNpemU6IDM2cHg7CiAgICBmb250LXdlaWdodDogOTAwOwogICAgbGluZS1oZWlnaHQ6IDE7CiAgfQoKICAuZHBpLXN0YXR1cy10ZXh0IHsgZm9udC1zaXplOiAxMXB4OyBjb2xvcjogdmFyKC0tZGltKTsgbWFyZ2luLXRvcDogNnB4OyB9CgogIC5kcGktZGV0YWlscyB7CiAgICBkaXNwbGF5OiBncmlkOwogICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxZnIgMWZyOwogICAgZ2FwOiAxMHB4OwogICAgbWFyZ2luLXRvcDogMTRweDsKICB9CgogIC5kcGktc3RhdCB7CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1iZyk7CiAgICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgcGFkZGluZzogMTBweDsKICAgIHRleHQtYWxpZ246IGNlbnRlcjsKICB9CgogIC5kcGktc3RhdC12YWwgeyBmb250LWZhbWlseTogJ09yYml0cm9uJywgbW9ub3NwYWNlOyBmb250LXNpemU6IDE2cHg7IGNvbG9yOiB2YXIoLS1hY2NlbnQpOyB9CiAgLmRwaS1zdGF0LWxibCB7IGZvbnQtc2l6ZTogOXB4OyBjb2xvcjogdmFyKC0tZGltKTsgbWFyZ2luLXRvcDogM3B4OyB9CgogIC8qIOKUgOKUgCBDb25uZWN0aW9uIGluZm8g4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAICovCiAgLmluZm8tcm93IHsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47CiAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgcGFkZGluZzogMTBweCAwOwogICAgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgICBmb250LXNpemU6IDEzcHg7CiAgfQoKICAuaW5mby1yb3c6bGFzdC1jaGlsZCB7IGJvcmRlci1ib3R0b206IG5vbmU7IH0KICAuaW5mby1rZXkgICB7IGNvbG9yOiB2YXIoLS1kaW0pOyBmb250LXNpemU6IDExcHg7IGxldHRlci1zcGFjaW5nOiAxcHg7IH0KICAuaW5mby12YWx1ZSB7IGNvbG9yOiB2YXIoLS1hY2NlbnQpOyBmb250LWZhbWlseTogJ1NoYXJlIFRlY2ggTW9ubycsIG1vbm9zcGFjZTsgfQogIC5pbmZvLXZhbHVlLmdyZWVuIHsgY29sb3I6IHZhcigtLWdyZWVuKTsgfQoKICAvKiDilIDilIAgVGFicyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAudGFicyB7IGRpc3BsYXk6IGZsZXg7IGdhcDogMnB4OyBtYXJnaW4tYm90dG9tOiAyMHB4OyB9CgogIC50YWItYnRuIHsKICAgIGJhY2tncm91bmQ6IHRyYW5zcGFyZW50OwogICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIGNvbG9yOiB2YXIoLS1kaW0pOwogICAgZm9udC1mYW1pbHk6IGluaGVyaXQ7CiAgICBmb250LXNpemU6IDExcHg7CiAgICBsZXR0ZXItc3BhY2luZzogMnB4OwogICAgcGFkZGluZzogOHB4IDE4cHg7CiAgICBjdXJzb3I6IHBvaW50ZXI7CiAgICB0cmFuc2l0aW9uOiBhbGwgLjJzOwogIH0KCiAgLnRhYi1idG4uYWN0aXZlIHsKICAgIGJvcmRlci1jb2xvcjogdmFyKC0tYWNjZW50KTsKICAgIGNvbG9yOiB2YXIoLS1hY2NlbnQpOwogICAgYmFja2dyb3VuZDogcmdiYSgwLDIxMiwyNTUsLjA1KTsKICB9CgogIC50YWItcGFuZSB7IGRpc3BsYXk6IG5vbmU7IH0KICAudGFiLXBhbmUuYWN0aXZlIHsgZGlzcGxheTogYmxvY2s7IH0KCiAgLyog4pSA4pSAIFZMRVNTIGxpbmsg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAICovCiAgLmxpbmstYm94IHsKICAgIGJhY2tncm91bmQ6IHZhcigtLWJnKTsKICAgIGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgICBwYWRkaW5nOiAxNHB4IDE2cHg7CiAgICBmb250LXNpemU6IDExcHg7CiAgICBjb2xvcjogdmFyKC0tZ3JlZW4pOwogICAgd29yZC1icmVhazogYnJlYWstYWxsOwogICAgbGluZS1oZWlnaHQ6IDEuNjsKICAgIG1hcmdpbi1ib3R0b206IDEycHg7CiAgICBjdXJzb3I6IHBvaW50ZXI7CiAgICB0cmFuc2l0aW9uOiBib3JkZXItY29sb3IgLjJzOwogICAgcG9zaXRpb246IHJlbGF0aXZlOwogIH0KCiAgLmxpbmstYm94OmhvdmVyIHsgYm9yZGVyLWNvbG9yOiB2YXIoLS1ncmVlbik7IH0KCiAgLmxpbmstY29weS1oaW50IHsKICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTsKICAgIHRvcDogNnB4OyByaWdodDogMTBweDsKICAgIGZvbnQtc2l6ZTogOXB4OwogICAgY29sb3I6IHZhcigtLWRpbSk7CiAgICBsZXR0ZXItc3BhY2luZzogMXB4OwogIH0KCiAgLmNvcGllZC10b2FzdCB7CiAgICBwb3NpdGlvbjogZml4ZWQ7CiAgICBib3R0b206IDMycHg7IHJpZ2h0OiAzMnB4OwogICAgYmFja2dyb3VuZDogdmFyKC0tZ3JlZW4pOwogICAgY29sb3I6IHZhcigtLWJnKTsKICAgIGZvbnQtZmFtaWx5OiAnT3JiaXRyb24nLCBtb25vc3BhY2U7CiAgICBmb250LXNpemU6IDExcHg7CiAgICBsZXR0ZXItc3BhY2luZzogMnB4OwogICAgcGFkZGluZzogMTJweCAyMHB4OwogICAgb3BhY2l0eTogMDsKICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgxMHB4KTsKICAgIHRyYW5zaXRpb246IGFsbCAuM3M7CiAgICB6LWluZGV4OiAyMDA7CiAgfQoKICAuY29waWVkLXRvYXN0LnNob3cgeyBvcGFjaXR5OiAxOyB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoMCk7IH0KCiAgLyog4pSA4pSAIFFSIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogIC5xci13cmFwIHsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICBnYXA6IDMycHg7CiAgICBmbGV4LXdyYXA6IHdyYXA7CiAgICBwYWRkaW5nOiA4cHggMDsKICB9CgogIC5xci1pdGVtIHsgdGV4dC1hbGlnbjogY2VudGVyOyB9CgogIC5xci1pbm5lciB7CiAgICB3aWR0aDogMTYwcHg7IGhlaWdodDogMTYwcHg7CiAgICBiYWNrZ3JvdW5kOiAjZmZmOwogICAgZGlzcGxheTogZmxleDsKICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsKICAgIG1hcmdpbjogMCBhdXRvIDEwcHg7CiAgICBwYWRkaW5nOiA4cHg7CiAgfQoKICAucXItaW5uZXIgY2FudmFzIHsgd2lkdGg6IDE0NHB4ICFpbXBvcnRhbnQ7IGhlaWdodDogMTQ0cHggIWltcG9ydGFudDsgfQoKICAucXItdGFnIHsKICAgIGZvbnQtc2l6ZTogMTBweDsKICAgIGxldHRlci1zcGFjaW5nOiAycHg7CiAgICBjb2xvcjogdmFyKC0tZGltKTsKICB9CgogIC8qIOKUgOKUgCBMb2dzIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogIC5sb2ctYm94IHsKICAgIGJhY2tncm91bmQ6IHZhcigtLWJnKTsKICAgIGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgICBwYWRkaW5nOiAxNHB4OwogICAgZm9udC1zaXplOiAxMXB4OwogICAgY29sb3I6ICM0YTk7CiAgICBoZWlnaHQ6IDI2MHB4OwogICAgb3ZlcmZsb3cteTogYXV0bzsKICAgIGxpbmUtaGVpZ2h0OiAxLjc7CiAgfQoKICAubG9nLWJveCAuZXJyIHsgY29sb3I6IHZhcigtLXJlZCk7IH0KICAubG9nLWJveCAud2FybiB7IGNvbG9yOiB2YXIoLS15ZWxsb3cpOyB9CgogIC8qIOKUgOKUgCBPcmJpdCBidXR0b24g4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAICovCiAgLm9yYml0LXNlY3Rpb24gewogICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgcGFkZGluZzogOHB4IDA7CiAgfQoKICAub3JiaXQtd2FybiB7CiAgICBmb250LXNpemU6IDExcHg7CiAgICBjb2xvcjogdmFyKC0tZGltKTsKICAgIG1hcmdpbi10b3A6IDE0cHg7CiAgICBsaW5lLWhlaWdodDogMS42OwogIH0KCiAgLm9yYml0LXJlc3VsdCB7CiAgICBtYXJnaW4tdG9wOiAxNnB4OwogICAgYmFja2dyb3VuZDogcmdiYSgxMjMsNDcsMjU1LC4xKTsKICAgIGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWFjY2VudDIpOwogICAgcGFkZGluZzogMTRweDsKICAgIGZvbnQtc2l6ZTogMTFweDsKICAgIGNvbG9yOiB2YXIoLS1hY2NlbnQyKTsKICAgIGxpbmUtaGVpZ2h0OiAxLjg7CiAgICBkaXNwbGF5OiBub25lOwogIH0KCiAgLyog4pSA4pSAIFJvdGF0aW9uIGNvdW50ZG93biDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAubmV4dC1yb3RhdGlvbiB7CiAgICBmb250LWZhbWlseTogJ09yYml0cm9uJywgbW9ub3NwYWNlOwogICAgZm9udC1zaXplOiAyMHB4OwogICAgY29sb3I6IHZhcigtLXllbGxvdyk7CiAgICBsZXR0ZXItc3BhY2luZzogM3B4OwogICAgdGV4dC1zaGFkb3c6IDAgMCAxMnB4IHJnYmEoMjU1LDIyMSw4NywuNCk7CiAgfQoKICAvKiDilIDilIAgVXB0aW1lIC8gZm9vdGVyIGJhciDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAuZm9vdGVyLWJhciB7CiAgICBtYXJnaW4tdG9wOiAzMnB4OwogICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgICBwYWRkaW5nLXRvcDogMTZweDsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBnYXA6IDMycHg7CiAgICBmb250LXNpemU6IDExcHg7CiAgICBjb2xvcjogdmFyKC0tZGltKTsKICAgIGZsZXgtd3JhcDogd3JhcDsKICB9CgogIC5mb290ZXItYmFyIHNwYW4geyBjb2xvcjogdmFyKC0tYWNjZW50KTsgfQoKICAvKiDilIDilIAgQmxpbmsgY3Vyc29yIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogIC5ibGluayB7IGFuaW1hdGlvbjogYmxpbmsgMXMgc3RlcC1lbmQgaW5maW5pdGU7IH0KICBAa2V5ZnJhbWVzIGJsaW5rIHsgNTAlIHsgb3BhY2l0eTogMDsgfSB9CgogIC8qIOKUgOKUgCBTY3JvbGxiYXIg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAICovCiAgOjotd2Via2l0LXNjcm9sbGJhciB7IHdpZHRoOiA2cHg7IH0KICA6Oi13ZWJraXQtc2Nyb2xsYmFyLXRyYWNrIHsgYmFja2dyb3VuZDogdmFyKC0tYmcpOyB9CiAgOjotd2Via2l0LXNjcm9sbGJhci10aHVtYiB7IGJhY2tncm91bmQ6IHZhcigtLWJvcmRlcik7IGJvcmRlci1yYWRpdXM6IDNweDsgfQogIDo6LXdlYmtpdC1zY3JvbGxiYXItdGh1bWI6aG92ZXIgeyBiYWNrZ3JvdW5kOiB2YXIoLS1kaW0pOyB9Cjwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+Cgo8IS0tIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAogICAgIEFVVEggT1ZFUkxBWQrilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZAgLS0+CjxkaXYgaWQ9ImF1dGgtb3ZlcmxheSI+CiAgPGRpdiBjbGFzcz0iYXV0aC1ib3giPgogICAgPGRpdiBjbGFzcz0iYXV0aC10aXRsZSI+Ly8gRUNMSVBTRSBBVVRIPC9kaXY+CiAgICA8aW5wdXQgaWQ9ImF1dGgtcGFzcyIgdHlwZT0icGFzc3dvcmQiIHBsYWNlaG9sZGVyPSLQktCS0JXQlNCY0KLQlSDQn9CQ0KDQntCb0KwiIGF1dG9jb21wbGV0ZT0ib2ZmIj4KICAgIDxidXR0b24gY2xhc3M9ImJ0biIgb25jbGljaz0iZG9BdXRoKCkiPtCS0J7QmdCi0Jgg0JIg0KHQmNCh0KLQldCc0KM8L2J1dHRvbj4KICAgIDxkaXYgaWQ9ImF1dGgtZXJyb3IiPjwvZGl2PgogIDwvZGl2PgogIDxkaXYgc3R5bGU9ImZvbnQtc2l6ZToxMXB4O2NvbG9yOnZhcigtLWRpbSk7bGV0dGVyLXNwYWNpbmc6MnB4OyI+RUNMSVBTRSB2MS4wIMK3IENPTlRST0wgTk9ERTxzcGFuIGNsYXNzPSJibGluayI+Xzwvc3Bhbj48L2Rpdj4KPC9kaXY+Cgo8IS0tIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAogICAgIE1BSU4gREFTSEJPQVJECuKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkCAtLT4KPGRpdiBpZD0ibWFpbiIgc3R5bGU9ImRpc3BsYXk6bm9uZSI+CjxkaXYgY2xhc3M9ImNvbnRhaW5lciI+CgogIDwhLS0gSGVhZGVyIC0tPgogIDxoZWFkZXI+CiAgICA8ZGl2IGNsYXNzPSJsb2dvIj4KICAgICAgPGRpdiBjbGFzcz0ibG9nby1kb3QiPjwvZGl2PgogICAgICBFQ0xJUFNFCiAgICA8L2Rpdj4KICAgIDxkaXYgY2xhc3M9ImhlYWRlci1tZXRhIj4KICAgICAgPGRpdj5TRVJWRVIgSVA6IDxzcGFuIGlkPSJzZXJ2ZXItaXAiPuKAlDwvc3Bhbj48L2Rpdj4KICAgICAgPGRpdj5VVEM6IDxzcGFuIGlkPSJjbG9jayI+4oCUPC9zcGFuPjwvZGl2PgogICAgICA8ZGl2PlVQVElNRTogPHNwYW4gaWQ9InVwdGltZSI+4oCUPC9zcGFuPjwvZGl2PgogICAgPC9kaXY+CiAgPC9oZWFkZXI+CgogIDwhLS0gRGFzaGJvYXJkIGdyaWQgLS0+CiAgPGRpdiBjbGFzcz0iZGFzaGJvYXJkIj4KCiAgICA8IS0tIOKUgOKUgCBTeXN0ZW0gSGVhbHRoIOKUgOKUgCAtLT4KICAgIDxkaXYgY2xhc3M9ImNhcmQgY29sLTQiPgogICAgICA8ZGl2IGNsYXNzPSJjYXJkLWxhYmVsIj5TeXN0ZW0gSGVhbHRoPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImhlYWx0aC1yaW5nIj4KICAgICAgICA8c3ZnIHZpZXdCb3g9IjAgMCAxMDAgMTAwIiB3aWR0aD0iMTIwIiBoZWlnaHQ9IjEyMCI+CiAgICAgICAgICA8Y2lyY2xlIGNsYXNzPSJyaW5nLWJnIiAgY3g9IjUwIiBjeT0iNTAiIHI9IjQ1Ii8+CiAgICAgICAgICA8Y2lyY2xlIGNsYXNzPSJyaW5nLXZhbCIgY3g9IjUwIiBjeT0iNTAiIHI9IjQ1IiBpZD0iaGVhbHRoLXJpbmciLz4KICAgICAgICA8L3N2Zz4KICAgICAgICA8ZGl2IGNsYXNzPSJoZWFsdGgtY2VudGVyIj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImhlYWx0aC1wY3QiIGlkPSJoZWFsdGgtcGN0Ij7igJQ8L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImhlYWx0aC1sYWJlbCI+SEVBTFRIPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgogICAgICA8ZGl2IHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjtmb250LXNpemU6MTJweDtjb2xvcjp2YXIoLS1kaW0pO21hcmdpbi10b3A6NHB4OyIgaWQ9ImhlYWx0aC10ZXh0Ij7Ql9Cw0LPRgNGD0LfQutCw4oCmPC9kaXY+CiAgICA8L2Rpdj4KCiAgICA8IS0tIOKUgOKUgCBEUEkgQWxlcnQgV2lkZ2V0IOKUgOKUgCAtLT4KICAgIDxkaXYgY2xhc3M9ImNhcmQgY29sLTgiPgogICAgICA8ZGl2IGNsYXNzPSJjYXJkLWxhYmVsIj5EUEkgSW50ZXJmZXJlbmNlIFNjb3JlPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImRwaS1nYXVnZS13cmFwIj4KICAgICAgICA8ZGl2IGNsYXNzPSJkcGktc2NvcmUtbnVtIiBpZD0iZHBpLXNjb3JlIiBzdHlsZT0iY29sb3I6dmFyKC0tZ3JlZW4pIj7igJQ8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJkcGktYmFyLWJnIj48ZGl2IGNsYXNzPSJkcGktYmFyLWZpbGwiIGlkPSJkcGktYmFyIj48L2Rpdj48L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJkcGktc3RhdHVzLXRleHQiIGlkPSJkcGktc3RhdHVzLXRleHQiPtCY0LfQvNC10YDQtdC90LjQteKApjwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9ImRwaS1kZXRhaWxzIj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImRwaS1zdGF0Ij4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iZHBpLXN0YXQtdmFsIiBpZD0iZHBpLWJsb2NrZWQiPuKAlDwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJkcGktc3RhdC1sYmwiPtCX0JDQkdCb0J7Qmi4g0KHQkNCZ0KLQqyAo0LzRgSk8L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZHBpLXN0YXQiPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJkcGktc3RhdC12YWwiIGlkPSJkcGktZGlyZWN0Ij7igJQ8L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iZHBpLXN0YXQtbGJsIj7Qn9Cg0K/QnNCr0JUg0KHQkNCZ0KLQqyAo0LzRgSk8L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZHBpLXN0YXQiPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJkcGktc3RhdC12YWwiIGlkPSJkcGktdGltZW91dHMiPuKAlDwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJkcGktc3RhdC1sYmwiPtCi0JDQmdCc0JDQo9Ci0Ks8L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZHBpLXN0YXQiPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJkcGktc3RhdC12YWwiIGlkPSJkcGktdXBkYXRlZCI+4oCUPC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImRwaS1zdGF0LWxibCI+0J7QkdCd0J7QktCb0JXQndCePC9kaXY+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgICA8YnV0dG9uIGNsYXNzPSJidG4iIHN0eWxlPSJtYXJnaW4tdG9wOjE0cHg7Zm9udC1zaXplOjEwcHg7bGV0dGVyLXNwYWNpbmc6MnB4OyIgb25jbGljaz0icmVmcmVzaERQSSgpIj7ihrsg0J7QkdCd0J7QktCY0KLQrCBEUEk8L2J1dHRvbj4KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KCiAgICA8IS0tIOKUgOKUgCBDb25uZWN0aW9uIEluZm8g4pSA4pSAIC0tPgogICAgPGRpdiBjbGFzcz0iY2FyZCBjb2wtNSI+CiAgICAgIDxkaXYgY2xhc3M9ImNhcmQtbGFiZWwiPtCf0LDRgNCw0LzQtdGC0YDRiyDQv9C+0LTQutC70Y7Rh9C10L3QuNGPPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImluZm8tcm93Ij4KICAgICAgICA8ZGl2IGNsYXNzPSJpbmZvLWtleSI+U05JPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iaW5mby12YWx1ZSIgaWQ9ImluZm8tc25pIj7igJQ8L2Rpdj4KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImluZm8tcm93Ij4KICAgICAgICA8ZGl2IGNsYXNzPSJpbmZvLWtleSI+U0hPUlQgSUQ8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJpbmZvLXZhbHVlIiBpZD0iaW5mby1zaWQiPuKAlDwvZGl2PgogICAgICA8L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0iaW5mby1yb3ciPgogICAgICAgIDxkaXYgY2xhc3M9ImluZm8ta2V5Ij5QT1JUIFRDUDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9ImluZm8tdmFsdWUgZ3JlZW4iPjQ0MzwvZGl2PgogICAgICA8L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0iaW5mby1yb3ciPgogICAgICAgIDxkaXYgY2xhc3M9ImluZm8ta2V5Ij5QT1JUIGdSUEM8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJpbmZvLXZhbHVlIGdyZWVuIj44NDQzPC9kaXY+CiAgICAgIDwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJpbmZvLXJvdyI+CiAgICAgICAgPGRpdiBjbGFzcz0iaW5mby1rZXkiPtCh0JvQldCU0KPQrtCp0JDQryDQoNCe0KLQkNCm0JjQrzwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9Im5leHQtcm90YXRpb24iIGlkPSJuZXh0LXJvdGF0aW9uIj7igJQ8L2Rpdj4KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImluZm8tcm93Ij4KICAgICAgICA8ZGl2IGNsYXNzPSJpbmZvLWtleSI+0J/QntCh0JvQldCU0J3Qr9CvINCg0J7QotCQ0KbQmNCvPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iaW5mby12YWx1ZSIgaWQ9ImluZm8tcm90YXRlZCIgc3R5bGU9ImZvbnQtc2l6ZToxMXB4Ij7igJQ8L2Rpdj4KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KCiAgICA8IS0tIOKUgOKUgCBFbWVyZ2VuY3kgT3JiaXQg4pSA4pSAIC0tPgogICAgPGRpdiBjbGFzcz0iY2FyZCBjb2wtNyI+CiAgICAgIDxkaXYgY2xhc3M9ImNhcmQtbGFiZWwiPtCt0LrRgdGC0YDQtdC90L3QsNGPINC+0YDQsdC40YLQsDwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJvcmJpdC1zZWN0aW9uIj4KICAgICAgICA8YnV0dG9uIGNsYXNzPSJidG4gYnRuLW9yYml0IiBzdHlsZT0id2lkdGg6MTAwJTtmb250LXNpemU6MTNweDtwYWRkaW5nOjIwcHg7bGV0dGVyLXNwYWNpbmc6NHB4OyIgaWQ9Im9yYml0LWJ0biIgb25jbGljaz0iZW1lcmdlbmN5T3JiaXQoKSI+CiAgICAgICAgICDwn5qAIEVNRVJHRU5DWSBPUkJJVAogICAgICAgIDwvYnV0dG9uPgogICAgICAgIDxkaXYgY2xhc3M9Im9yYml0LXdhcm4iPgogICAgICAgICAg0J3QtdC80LXQtNC70LXQvdC90LDRjyDRgdC80LXQvdCwINCy0YHQtdGFINC60LvRjtGH0LXQuSwgU2hvcnRJRCDQuCBTTkkuPGJyPgogICAgICAgICAg0JLRgdC1INCw0LrRgtC40LLQvdGL0LUg0YHQvtC10LTQuNC90LXQvdC40Y8g0LHRg9C00YPRgiDQv9C10YDQtdC/0L7QtNC60LvRjtGH0LXQvdGLINCw0LLRgtC+0LzQsNGC0LjRh9C10YHQutC4Ljxicj4KICAgICAgICAgIDxzcGFuIHN0eWxlPSJjb2xvcjp2YXIoLS15ZWxsb3cpOyI+0JjRgdC/0L7Qu9GM0LfRg9C50YLQtSDQv9GA0Lgg0L7QsdC90LDRgNGD0LbQtdC90LjQuCBEUEkt0LHQu9C+0LrQuNGA0L7QstC60LguPC9zcGFuPgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9Im9yYml0LXJlc3VsdCIgaWQ9Im9yYml0LXJlc3VsdCI+PC9kaXY+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CgogICAgPCEtLSDilIDilIAgVkxFU1MgTGlua3MgKyBRUiDilIDilIAgLS0+CiAgICA8ZGl2IGNsYXNzPSJjYXJkIGNvbC0xMiI+CiAgICAgIDxkaXYgY2xhc3M9ImNhcmQtbGFiZWwiPlZMRVNTINCh0YHRi9C70LrQuCDQuCBRUi3QutC+0LTRizwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJ0YWJzIj4KICAgICAgICA8YnV0dG9uIGNsYXNzPSJ0YWItYnRuIGFjdGl2ZSIgb25jbGljaz0ic3dpdGNoVGFiKCd0Y3AnKSI+VENQIFBPUlQgNDQzPC9idXR0b24+CiAgICAgICAgPGJ1dHRvbiBjbGFzcz0idGFiLWJ0biIgb25jbGljaz0ic3dpdGNoVGFiKCdncnBjJykiPmdSUEMgUE9SVCA4NDQzPC9idXR0b24+CiAgICAgICAgPGJ1dHRvbiBjbGFzcz0idGFiLWJ0biIgb25jbGljaz0ic3dpdGNoVGFiKCdxcicpIj5RUiDQmtCe0JTQqzwvYnV0dG9uPgogICAgICA8L2Rpdj4KCiAgICAgIDxkaXYgY2xhc3M9InRhYi1wYW5lIGFjdGl2ZSIgaWQ9InRhYi10Y3AiPgogICAgICAgIDxkaXYgY2xhc3M9ImxpbmstYm94IiBpZD0ibGluay10Y3AiIG9uY2xpY2s9ImNvcHlMaW5rKCd0Y3AnKSI+CiAgICAgICAgICA8c3BhbiBjbGFzcz0ibGluay1jb3B5LWhpbnQiPtCd0JDQltCc0JjQotCVINCU0JvQryDQmtCe0J/QmNCg0J7QktCQ0J3QmNCvPC9zcGFuPgogICAgICAgICAgPHNwYW4gaWQ9ImxpbmstdGNwLXRleHQiPtCX0LDQs9GA0YPQt9C60LDigKY8L3NwYW4+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBzdHlsZT0iZm9udC1zaXplOjExcHg7Y29sb3I6dmFyKC0tZGltKTtsaW5lLWhlaWdodDoxLjg7bWFyZ2luLXRvcDo0cHg7Ij4KICAgICAgICAgIOKaoSDQn9GA0L7RgtC+0LrQvtC7OiBWTEVTUyArIFJlYWxpdHkgKFRDUCkgwrcg0J/QvtGC0L7QujogeHRscy1ycHJ4LXZpc2lvbiDCtyB1VExTOiBTYWZhcmkKICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CgogICAgICA8ZGl2IGNsYXNzPSJ0YWItcGFuZSIgaWQ9InRhYi1ncnBjIj4KICAgICAgICA8ZGl2IGNsYXNzPSJsaW5rLWJveCIgaWQ9ImxpbmstZ3JwYyIgb25jbGljaz0iY29weUxpbmsoJ2dycGMnKSI+CiAgICAgICAgICA8c3BhbiBjbGFzcz0ibGluay1jb3B5LWhpbnQiPtCd0JDQltCc0JjQotCVINCU0JvQryDQmtCe0J/QmNCg0J7QktCQ0J3QmNCvPC9zcGFuPgogICAgICAgICAgPHNwYW4gaWQ9ImxpbmstZ3JwYy10ZXh0Ij7Ql9Cw0LPRgNGD0LfQutCw4oCmPC9zcGFuPgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgc3R5bGU9ImZvbnQtc2l6ZToxMXB4O2NvbG9yOnZhcigtLWRpbSk7bGluZS1oZWlnaHQ6MS44O21hcmdpbi10b3A6NHB4OyI+CiAgICAgICAgICDimqEg0J/RgNC+0YLQvtC60L7QuzogVkxFU1MgKyBSZWFsaXR5IChnUlBDKSDCtyDQoNC10LbQuNC8OiBtdWx0aVBhdGggwrcgdVRMUzogQ2hyb21lCiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgoKICAgICAgPGRpdiBjbGFzcz0idGFiLXBhbmUiIGlkPSJ0YWItcXIiPgogICAgICAgIDxkaXYgY2xhc3M9InFyLXdyYXAiIGlkPSJxci13cmFwIj4KICAgICAgICAgIDxkaXYgY2xhc3M9InFyLWl0ZW0iPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJxci1pbm5lciI+PGRpdiBpZD0icXItdGNwIj48L2Rpdj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzcz0icXItdGFnIj5UQ1AgwrcgUE9SVCA0NDM8L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0icXItaXRlbSI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9InFyLWlubmVyIj48ZGl2IGlkPSJxci1ncnBjIj48L2Rpdj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzcz0icXItdGFnIj5nUlBDIMK3IFBPUlQgODQ0MzwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7Zm9udC1zaXplOjExcHg7Y29sb3I6dmFyKC0tZGltKTttYXJnaW4tdG9wOjhweDsiPgogICAgICAgICAg0J7RgtGB0LrQsNC90LjRgNGD0LnRgtC1INCyIFNoYWRvd3JvY2tldCAvIFYycmF5TkcgLyBOZWtvQm94CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CgogICAgPCEtLSDilIDilIAgTG9ncyDilIDilIAgLS0+CiAgICA8ZGl2IGNsYXNzPSJjYXJkIGNvbC0xMiI+CiAgICAgIDxkaXYgY2xhc3M9ImNhcmQtbGFiZWwiIHN0eWxlPSJqdXN0aWZ5LWNvbnRlbnQ6c3BhY2UtYmV0d2VlbjtkaXNwbGF5OmZsZXg7Ij4KICAgICAgICA8c3Bhbj7Qm9C+0LPQuCBYcmF5PC9zcGFuPgogICAgICAgIDxidXR0b24gY2xhc3M9InRhYi1idG4iIG9uY2xpY2s9ImxvYWRMb2dzKCkiIHN0eWxlPSJwYWRkaW5nOjRweCAxMnB4O2ZvbnQtc2l6ZTo5cHg7Ij7ihrsg0J7QkdCd0J7QktCY0KLQrDwvYnV0dG9uPgogICAgICA8L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0idGFicyI+CiAgICAgICAgPGJ1dHRvbiBjbGFzcz0idGFiLWJ0biBhY3RpdmUiIG9uY2xpY2s9InN3aXRjaExvZ1RhYignYWNjZXNzJykiPkFDQ0VTUzwvYnV0dG9uPgogICAgICAgIDxidXR0b24gY2xhc3M9InRhYi1idG4iIG9uY2xpY2s9InN3aXRjaExvZ1RhYignZXJyb3InKSI+RVJST1I8L2J1dHRvbj4KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImxvZy1ib3giIGlkPSJsb2ctYm94Ij7Ql9Cw0LPRgNGD0LfQutCwINC70L7Qs9C+0LLigKY8L2Rpdj4KICAgIDwvZGl2PgoKICA8L2Rpdj48IS0tIC9kYXNoYm9hcmQgLS0+CgogIDxkaXYgY2xhc3M9ImZvb3Rlci1iYXIiPgogICAgPGRpdj5FQ0xJUFNFIFZQTiDCtyA8c3Bhbj52MS4wLjA8L3NwYW4+PC9kaXY+CiAgICA8ZGl2PkVOR0lORTogPHNwYW4+WHJheS1jb3JlPC9zcGFuPjwvZGl2PgogICAgPGRpdj5QUk9UTzogPHNwYW4+VkxFU1MrUmVhbGl0eTwvc3Bhbj48L2Rpdj4KICAgIDxkaXY+T0JGUzogPHNwYW4+dVRMUyArIFRDUCBGcmFnbWVudGF0aW9uPC9zcGFuPjwvZGl2PgogICAgPGRpdj48c3BhbiBjbGFzcz0iYmxpbmsiPuKXjzwvc3Bhbj4gT05MSU5FPC9kaXY+CiAgPC9kaXY+Cgo8L2Rpdj48IS0tIC9jb250YWluZXIgLS0+CjwvZGl2PjwhLS0gL21haW4gLS0+Cgo8ZGl2IGNsYXNzPSJjb3BpZWQtdG9hc3QiIGlkPSJ0b2FzdCI+0KHQmtCe0J/QmNCg0J7QktCQ0J3QnjwvZGl2PgoKPHNjcmlwdD4KLy8g4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACi8vIEF1dGgKLy8g4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACmxldCBBVVRIX0hFQURFUiA9ICcnOwoKZnVuY3Rpb24gbWFrZUJhc2ljKHBhc3MpIHsKICByZXR1cm4gJ0Jhc2ljICcgKyBidG9hKCdlY2xpcHNlOicgKyBwYXNzKTsKfQoKYXN5bmMgZnVuY3Rpb24gZG9BdXRoKCkgewogIGNvbnN0IHBhc3MgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXV0aC1wYXNzJykudmFsdWUudHJpbSgpOwogIGlmICghcGFzcykgcmV0dXJuOwogIGNvbnN0IGhlYWRlciA9IG1ha2VCYXNpYyhwYXNzKTsKICB0cnkgewogICAgY29uc3QgciA9IGF3YWl0IGZldGNoKCcvYXBpL3N0YXR1cycsIHsgaGVhZGVyczogeyBBdXRob3JpemF0aW9uOiBoZWFkZXIgfSB9KTsKICAgIGlmIChyLm9rKSB7CiAgICAgIEFVVEhfSEVBREVSID0gaGVhZGVyOwogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXV0aC1vdmVybGF5Jykuc3R5bGUuZGlzcGxheSA9ICdub25lJzsKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ21haW4nKS5zdHlsZS5kaXNwbGF5ID0gJ2Jsb2NrJzsKICAgICAgaW5pdERhc2hib2FyZCgpOwogICAgfSBlbHNlIHsKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2F1dGgtZXJyb3InKS50ZXh0Q29udGVudCA9ICcvLyDQlNCe0KHQotCj0J8g0JfQkNCf0KDQldCp0IHQnSc7CiAgICB9CiAgfSBjYXRjaChlKSB7CiAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXV0aC1lcnJvcicpLnRleHRDb250ZW50ID0gJy8vINCe0KjQmNCR0JrQkCDQodCe0JXQlNCY0J3QldCd0JjQryc7CiAgfQp9Cgpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXV0aC1wYXNzJykuYWRkRXZlbnRMaXN0ZW5lcigna2V5ZG93bicsIGUgPT4gewogIGlmIChlLmtleSA9PT0gJ0VudGVyJykgZG9BdXRoKCk7Cn0pOwoKLy8g4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACi8vIEFQSSBjYWxscwovLyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKYXN5bmMgZnVuY3Rpb24gYXBpKHBhdGgsIG1ldGhvZD0nR0VUJykgewogIGNvbnN0IHIgPSBhd2FpdCBmZXRjaChwYXRoLCB7IG1ldGhvZCwgaGVhZGVyczogeyBBdXRob3JpemF0aW9uOiBBVVRIX0hFQURFUiB9IH0pOwogIGlmICghci5vaykgdGhyb3cgbmV3IEVycm9yKHIuc3RhdHVzKTsKICByZXR1cm4gci5qc29uKCk7Cn0KCi8vIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAovLyBJbml0Ci8vIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgApmdW5jdGlvbiBpbml0RGFzaGJvYXJkKCkgewogIHVwZGF0ZUNsb2NrKCk7CiAgc2V0SW50ZXJ2YWwodXBkYXRlQ2xvY2ssIDEwMDApOwogIGxvYWRTdGF0dXMoKTsKICBsb2FkTGlua3MoKTsKICBsb2FkTG9ncygpOwogIHNldEludGVydmFsKGxvYWRTdGF0dXMsIDMwMDAwKTsKICBzZXRJbnRlcnZhbChsb2FkTGlua3MsIDYwMDAwKTsKfQoKZnVuY3Rpb24gdXBkYXRlQ2xvY2soKSB7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2Nsb2NrJykudGV4dENvbnRlbnQgPSBuZXcgRGF0ZSgpLnRvVVRDU3RyaW5nKCkuc2xpY2UoMTcsMjUpOwp9CgpmdW5jdGlvbiBmbXRVcHRpbWUoc2VjKSB7CiAgY29uc3QgZCA9IE1hdGguZmxvb3Ioc2VjIC8gODY0MDApOwogIGNvbnN0IGggPSBNYXRoLmZsb29yKChzZWMgJSA4NjQwMCkgLyAzNjAwKTsKICBjb25zdCBtID0gTWF0aC5mbG9vcigoc2VjICUgMzYwMCkgLyA2MCk7CiAgcmV0dXJuIChkID4gMCA/IGQgKyAnZCAnIDogJycpICsgaCArICdoICcgKyBtICsgJ20nOwp9Cgphc3luYyBmdW5jdGlvbiBsb2FkU3RhdHVzKCkgewogIHRyeSB7CiAgICBjb25zdCBzID0gYXdhaXQgYXBpKCcvYXBpL3N0YXR1cycpOwogICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3NlcnZlci1pcCcpLnRleHRDb250ZW50ID0gcy5zZXJ2ZXJfaXAgfHwgJ+KAlCc7CiAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndXB0aW1lJykudGV4dENvbnRlbnQgPSBzLnVwdGltZV9zZWMgPyBmbXRVcHRpbWUocy51cHRpbWVfc2VjKSA6ICfigJQnOwogICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2luZm8tc25pJykudGV4dENvbnRlbnQgPSBzLnNuaSB8fCAn4oCUJzsKICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdpbmZvLXNpZCcpLnRleHRDb250ZW50ID0gcy5zaG9ydF9pZCB8fCAn4oCUJzsKICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdpbmZvLXJvdGF0ZWQnKS50ZXh0Q29udGVudCA9IHMucm90YXRlZF9hdCA/IHMucm90YXRlZF9hdC5zbGljZSgwLDE5KS5yZXBsYWNlKCdUJywnICcpIDogJ+KAlCc7CgogICAgLy8gTmV4dCByb3RhdGlvbiAoYXNzdW1lIDI0aCBjeWNsZSBmcm9tIHJvdGF0ZWRfYXQpCiAgICBpZiAocy5yb3RhdGVkX2F0KSB7CiAgICAgIGNvbnN0IG5leHQgPSBuZXcgRGF0ZShuZXcgRGF0ZShzLnJvdGF0ZWRfYXQpLmdldFRpbWUoKSArIDI0KjM2MDAqMTAwMCk7CiAgICAgIGNvbnN0IGRpZmYgPSBNYXRoLm1heCgwLCBuZXh0IC0gRGF0ZS5ub3coKSk7CiAgICAgIGNvbnN0IGhoID0gTWF0aC5mbG9vcihkaWZmLzM2MDAwMDApOwogICAgICBjb25zdCBtbSA9IE1hdGguZmxvb3IoKGRpZmYlMzYwMDAwMCkvNjAwMDApOwogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbmV4dC1yb3RhdGlvbicpLnRleHRDb250ZW50ID0gaGggKyAnaCAnICsgbW0gKyAnbSc7CiAgICB9CgogICAgLy8gSGVhbHRoIHNjb3JlIChpbnZlcnNlIG9mIERQSSBzY29yZSkKICAgIHVwZGF0ZURQSShzLmRwaSk7CgogICAgLy8gSGVhbHRoIHJpbmcKICAgIGNvbnN0IHNjb3JlID0gcy5kcGkgPyBNYXRoLm1heCgwLCAxMDAgLSBzLmRwaS5zY29yZSkgOiAxMDA7CiAgICBzZXRIZWFsdGhSaW5nKHNjb3JlKTsKICB9IGNhdGNoKGUpIHsKICAgIGNvbnNvbGUuZXJyb3IoZSk7CiAgfQp9CgpmdW5jdGlvbiBzZXRIZWFsdGhSaW5nKHBjdCkgewogIGNvbnN0IHJpbmcgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVhbHRoLXJpbmcnKTsKICBjb25zdCBjaXJjdW1mZXJlbmNlID0gMjgzOwogIGNvbnN0IG9mZnNldCA9IGNpcmN1bWZlcmVuY2UgLSAocGN0IC8gMTAwKSAqIGNpcmN1bWZlcmVuY2U7CiAgcmluZy5zdHlsZS5zdHJva2VEYXNob2Zmc2V0ID0gb2Zmc2V0OwogIGNvbnN0IGNvbG9yID0gcGN0ID4gNzAgPyAndmFyKC0tZ3JlZW4pJyA6IHBjdCA+IDQwID8gJ3ZhcigtLXllbGxvdyknIDogJ3ZhcigtLXJlZCknOwogIHJpbmcuc3R5bGUuc3Ryb2tlID0gY29sb3I7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2hlYWx0aC1wY3QnKS50ZXh0Q29udGVudCA9IHBjdCArICclJzsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVhbHRoLXBjdCcpLnN0eWxlLmNvbG9yID0gY29sb3I7CiAgY29uc3QgdGV4dHMgPSBbJ9Ca0KDQmNCi0JjQp9Cd0J4nLCAn0KPQk9Cg0J7Ql9CQJywgJ9Cd0J7QoNCc0JAnLCAn0J7QotCb0JjQp9Cd0J4nLCAn0JjQlNCV0JDQm9Cs0J3QniddOwogIGNvbnN0IGlkeCA9IE1hdGgubWluKDQsIE1hdGguZmxvb3IocGN0IC8gMjEpKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVhbHRoLXRleHQnKS50ZXh0Q29udGVudCA9IHRleHRzW2lkeF07Cn0KCmZ1bmN0aW9uIHVwZGF0ZURQSShkcGkpIHsKICBpZiAoIWRwaSB8fCAhZHBpLnVwZGF0ZWRfYXQpIHJldHVybjsKICBjb25zdCBzY29yZSA9IGRwaS5zY29yZSB8fCAwOwogIGNvbnN0IGVsID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2RwaS1zY29yZScpOwogIGVsLnRleHRDb250ZW50ID0gc2NvcmU7CiAgZWwuc3R5bGUuY29sb3IgPSBzY29yZSA8IDMwID8gJ3ZhcigtLWdyZWVuKScgOiBzY29yZSA8IDYwID8gJ3ZhcigtLXllbGxvdyknIDogJ3ZhcigtLXJlZCknOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdkcGktYmFyJykuc3R5bGUud2lkdGggPSBzY29yZSArICclJzsKCiAgY29uc3Qgc3RhdHVzZXMgPSBbJ9Cn0JjQodCi0J4g4oCUIERQSSDQndCVINCe0JHQndCQ0KDQo9CW0JXQnScsICfQodCb0JDQkdCe0JUg0JLQnNCV0KjQkNCi0JXQm9Cs0KHQotCS0J4nLCAn0KPQnNCV0KDQldCd0J3QntCVINCX0JDQnNCV0JTQm9CV0J3QmNCVJywgJ9Ch0JjQm9Cs0J3QkNCvINCR0JvQntCa0JjQoNCe0JLQmtCQJ107CiAgY29uc3QgaWR4ID0gc2NvcmUgPCAyNSA/IDAgOiBzY29yZSA8IDUwID8gMSA6IHNjb3JlIDwgNzUgPyAyIDogMzsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZHBpLXN0YXR1cy10ZXh0JykudGV4dENvbnRlbnQgPSBzdGF0dXNlc1tpZHhdOwoKICBjb25zdCBkZXQgPSBkcGkuZGV0YWlscyB8fCB7fTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZHBpLWJsb2NrZWQnKS50ZXh0Q29udGVudCA9IGRldC5hdmdfYmxvY2tlZF9tcyA/IE1hdGgucm91bmQoZGV0LmF2Z19ibG9ja2VkX21zKSA6ICfigJQnOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdkcGktZGlyZWN0JykudGV4dENvbnRlbnQgID0gZGV0LmF2Z19kaXJlY3RfbXMgID8gTWF0aC5yb3VuZChkZXQuYXZnX2RpcmVjdF9tcykgIDogJ+KAlCc7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2RwaS10aW1lb3V0cycpLnRleHRDb250ZW50ID0gZGV0LmJsb2NrZWRfdGltZW91dHMgPz8gJ+KAlCc7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2RwaS11cGRhdGVkJykudGV4dENvbnRlbnQgID0gZHBpLnVwZGF0ZWRfYXQgPyBkcGkudXBkYXRlZF9hdC5zbGljZSgxMSwxOSkgOiAn4oCUJzsKfQoKYXN5bmMgZnVuY3Rpb24gcmVmcmVzaERQSSgpIHsKICBhd2FpdCBhcGkoJy9hcGkvZHBpL3JlZnJlc2gnLCAnUE9TVCcpOwogIHNldFRpbWVvdXQobG9hZFN0YXR1cywgMzAwMCk7Cn0KCi8vIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAovLyBMaW5rcyAmIFFSCi8vIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgApsZXQgbGlua3MgPSB7fTsKbGV0IHFyUmVuZGVyZWQgPSBmYWxzZTsKCmFzeW5jIGZ1bmN0aW9uIGxvYWRMaW5rcygpIHsKICB0cnkgewogICAgbGlua3MgPSBhd2FpdCBhcGkoJy9hcGkvbGlua3MnKTsKICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsaW5rLXRjcC10ZXh0JykudGV4dENvbnRlbnQgID0gbGlua3MudGNwOwogICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2xpbmstZ3JwYy10ZXh0JykudGV4dENvbnRlbnQgPSBsaW5rcy5ncnBjOwogICAgcmVuZGVyUVIoKTsKICB9IGNhdGNoKGUpIHsKICAgIGNvbnNvbGUuZXJyb3IoZSk7CiAgfQp9CgpmdW5jdGlvbiByZW5kZXJRUigpIHsKICBpZiAoIWxpbmtzLnRjcCkgcmV0dXJuOwogIFsndGNwJywnZ3JwYyddLmZvckVhY2godCA9PiB7CiAgICBjb25zdCBlbCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdxci0nICsgdCk7CiAgICBlbC5pbm5lckhUTUwgPSAnJzsKICAgIG5ldyBRUkNvZGUoZWwsIHsKICAgICAgdGV4dDogbGlua3NbdF0sCiAgICAgIHdpZHRoOiAxNDQsIGhlaWdodDogMTQ0LAogICAgICBjb2xvckRhcms6ICcjMDAwMDAwJywgY29sb3JMaWdodDogJyNmZmZmZmYnLAogICAgICBjb3JyZWN0TGV2ZWw6IFFSQ29kZS5Db3JyZWN0TGV2ZWwuTQogICAgfSk7CiAgfSk7Cn0KCmZ1bmN0aW9uIGNvcHlMaW5rKHR5cGUpIHsKICBjb25zdCB0ZXh0ID0gbGlua3NbdHlwZV07CiAgaWYgKCF0ZXh0KSByZXR1cm47CiAgbmF2aWdhdG9yLmNsaXBib2FyZC53cml0ZVRleHQodGV4dCkudGhlbigoKSA9PiBzaG93VG9hc3QoKSk7Cn0KCmZ1bmN0aW9uIHNob3dUb2FzdCgpIHsKICBjb25zdCB0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3RvYXN0Jyk7CiAgdC5jbGFzc0xpc3QuYWRkKCdzaG93Jyk7CiAgc2V0VGltZW91dCgoKSA9PiB0LmNsYXNzTGlzdC5yZW1vdmUoJ3Nob3cnKSwgMjAwMCk7Cn0KCi8vIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAovLyBUYWJzCi8vIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgApmdW5jdGlvbiBzd2l0Y2hUYWIobmFtZSkgewogIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJy50YWItcGFuZScpLmZvckVhY2gocCA9PiBwLmNsYXNzTGlzdC5yZW1vdmUoJ2FjdGl2ZScpKTsKICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCcudGFicyAudGFiLWJ0bicpLmZvckVhY2goYiA9PiBiLmNsYXNzTGlzdC5yZW1vdmUoJ2FjdGl2ZScpKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndGFiLScgKyBuYW1lKS5jbGFzc0xpc3QuYWRkKCdhY3RpdmUnKTsKICBldmVudC50YXJnZXQuY2xhc3NMaXN0LmFkZCgnYWN0aXZlJyk7Cn0KCmxldCBjdXJyZW50TG9nVGFiID0gJ2FjY2Vzcyc7CmxldCBsb2dzRGF0YSA9IHt9OwoKZnVuY3Rpb24gc3dpdGNoTG9nVGFiKG5hbWUpIHsKICBjdXJyZW50TG9nVGFiID0gbmFtZTsKICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCcudGFicycpWzFdLnF1ZXJ5U2VsZWN0b3JBbGwoJy50YWItYnRuJykuZm9yRWFjaChiID0+IGIuY2xhc3NMaXN0LnJlbW92ZSgnYWN0aXZlJykpOwogIGV2ZW50LnRhcmdldC5jbGFzc0xpc3QuYWRkKCdhY3RpdmUnKTsKICByZW5kZXJMb2dzKCk7Cn0KCmFzeW5jIGZ1bmN0aW9uIGxvYWRMb2dzKCkgewogIHRyeSB7CiAgICBsb2dzRGF0YSA9IGF3YWl0IGFwaSgnL2FwaS9sb2dzP2xpbmVzPTgwJyk7CiAgICByZW5kZXJMb2dzKCk7CiAgfSBjYXRjaChlKSB7fQp9CgpmdW5jdGlvbiByZW5kZXJMb2dzKCkgewogIGNvbnN0IGJveCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2ctYm94Jyk7CiAgY29uc3QgbGluZXMgPSBsb2dzRGF0YVtjdXJyZW50TG9nVGFiXSB8fCBbXTsKICBpZiAoIWxpbmVzLmxlbmd0aCkgeyBib3gudGV4dENvbnRlbnQgPSAnLy8g0J3QtdGCINC30LDQv9C40YHQtdC5JzsgcmV0dXJuOyB9CiAgYm94LmlubmVySFRNTCA9IGxpbmVzLm1hcChsID0+IHsKICAgIGNvbnN0IGNscyA9IGwuaW5jbHVkZXMoJ1tFcnJvcl0nKSB8fCBsLmluY2x1ZGVzKCdlcnJvcicpID8gJ2VycicKICAgICAgICAgICAgICA6IGwuaW5jbHVkZXMoJ1tXYXJuaW5nXScpID8gJ3dhcm4nIDogJyc7CiAgICByZXR1cm4gYDxkaXYgY2xhc3M9IiR7Y2xzfSI+JHtlc2NIdG1sKGwpfTwvZGl2PmA7CiAgfSkuam9pbignJyk7CiAgYm94LnNjcm9sbFRvcCA9IGJveC5zY3JvbGxIZWlnaHQ7Cn0KCmZ1bmN0aW9uIGVzY0h0bWwocykgewogIHJldHVybiBzLnJlcGxhY2UoLyYvZywnJmFtcDsnKS5yZXBsYWNlKC88L2csJyZsdDsnKS5yZXBsYWNlKC8+L2csJyZndDsnKTsKfQoKLy8g4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACi8vIEVtZXJnZW5jeSBPcmJpdAovLyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKYXN5bmMgZnVuY3Rpb24gZW1lcmdlbmN5T3JiaXQoKSB7CiAgY29uc3QgYnRuID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ29yYml0LWJ0bicpOwogIGNvbnN0IHJlcyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvcmJpdC1yZXN1bHQnKTsKICBidG4uY2xhc3NMaXN0LmFkZCgnbG9hZGluZycpOwogIGJ0bi5kaXNhYmxlZCA9IHRydWU7CiAgYnRuLnRleHRDb250ZW50ID0gJ+KPsyDQktCr0J/QntCb0J3Qr9CV0KLQodCvINCg0J7QotCQ0KbQmNCv4oCmJzsKICByZXMuc3R5bGUuZGlzcGxheSA9ICdub25lJzsKCiAgdHJ5IHsKICAgIGNvbnN0IGRhdGEgPSBhd2FpdCBhcGkoJy9hcGkvcm90YXRlJywgJ1BPU1QnKTsKICAgIGJ0bi50ZXh0Q29udGVudCA9ICfinIUg0J7QoNCR0JjQotCQINCh0JzQldCd0JXQndCQJzsKICAgIHJlcy5zdHlsZS5kaXNwbGF5ID0gJ2Jsb2NrJzsKICAgIHJlcy5pbm5lckhUTUwgPSBgCiAgICAgIC8vINCg0J7QotCQ0KbQmNCvINCS0KvQn9Ce0JvQndCV0J3QkDxicj4KICAgICAgTkVXX1NOSSAgICAgIDogJHtkYXRhLm5ld19zbml9PGJyPgogICAgICBORVdfU0hPUlRfSUQgOiAke2RhdGEubmV3X3Nob3J0X2lkfTxicj4KICAgICAgVElNRVNUQU1QICAgIDogJHtkYXRhLnJvdGF0ZWRfYXR9PGJyPgogICAgYDsKICAgIGxpbmtzID0geyB0Y3A6IGRhdGEudGNwX2xpbmssIGdycGM6IGRhdGEuZ3JwY19saW5rIH07CiAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbGluay10Y3AtdGV4dCcpLnRleHRDb250ZW50ICA9IGRhdGEudGNwX2xpbms7CiAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbGluay1ncnBjLXRleHQnKS50ZXh0Q29udGVudCA9IGRhdGEuZ3JwY19saW5rOwogICAgcmVuZGVyUVIoKTsKICAgIGF3YWl0IGxvYWRTdGF0dXMoKTsKCiAgICBzZXRUaW1lb3V0KCgpID0+IHsKICAgICAgYnRuLnRleHRDb250ZW50ID0gJ/CfmoAgRU1FUkdFTkNZIE9SQklUJzsKICAgICAgYnRuLmRpc2FibGVkID0gZmFsc2U7CiAgICAgIGJ0bi5jbGFzc0xpc3QucmVtb3ZlKCdsb2FkaW5nJyk7CiAgICB9LCA1MDAwKTsKICB9IGNhdGNoKGUpIHsKICAgIGJ0bi50ZXh0Q29udGVudCA9ICfinYwg0J7QqNCY0JHQmtCQIOKAlCDQn9Ce0JLQotCe0KAg0KfQldCg0JXQlyA10YEnOwogICAgc2V0VGltZW91dCgoKSA9PiB7CiAgICAgIGJ0bi50ZXh0Q29udGVudCA9ICfwn5qAIEVNRVJHRU5DWSBPUkJJVCc7CiAgICAgIGJ0bi5kaXNhYmxlZCA9IGZhbHNlOwogICAgICBidG4uY2xhc3NMaXN0LnJlbW92ZSgnbG9hZGluZycpOwogICAgfSwgNTAwMCk7CiAgfQp9Cjwvc2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4K"    "${INSTALL_DIR}/frontend/index.html"
decode_file "d29ya2VyX3Byb2Nlc3NlcyBhdXRvOwpldmVudHMgeyB3b3JrZXJfY29ubmVjdGlvbnMgMTAyNDsgfQoKaHR0cCB7CiAgICBpbmNsdWRlICAgICAgIC9ldGMvbmdpbngvbWltZS50eXBlczsKICAgIGRlZmF1bHRfdHlwZSAgYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtOwogICAgc2VuZGZpbGUgICAgICBvbjsKICAgIGtlZXBhbGl2ZV90aW1lb3V0IDY1OwoKICAgIGd6aXAgb247CiAgICBnemlwX3R5cGVzIHRleHQvcGxhaW4gdGV4dC9jc3MgYXBwbGljYXRpb24vanNvbiBhcHBsaWNhdGlvbi9qYXZhc2NyaXB0OwoKICAgIHNlcnZlciB7CiAgICAgICAgbGlzdGVuIDgwOwogICAgICAgIHNlcnZlcl9uYW1lIF87CgogICAgICAgIHJvb3QgL3Vzci9zaGFyZS9uZ2lueC9odG1sOwogICAgICAgIGluZGV4IGluZGV4Lmh0bWw7CgogICAgICAgICMgQVBJIHByb3h5IOKGkiBGYXN0QVBJIGJhY2tlbmQKICAgICAgICBsb2NhdGlvbiAvYXBpLyB7CiAgICAgICAgICAgIHByb3h5X3Bhc3MgICAgICAgICBodHRwOi8vZWNsaXBzZV9iYWNrZW5kOjgwODA7CiAgICAgICAgICAgIHByb3h5X2h0dHBfdmVyc2lvbiAxLjE7CiAgICAgICAgICAgIHByb3h5X3NldF9oZWFkZXIgICBIb3N0ICRob3N0OwogICAgICAgICAgICBwcm94eV9zZXRfaGVhZGVyICAgWC1SZWFsLUlQICRyZW1vdGVfYWRkcjsKICAgICAgICAgICAgcHJveHlfcmVhZF90aW1lb3V0IDYwOwogICAgICAgIH0KCiAgICAgICAgbG9jYXRpb24gL2hlYWx0aCB7CiAgICAgICAgICAgIHByb3h5X3Bhc3MgaHR0cDovL2VjbGlwc2VfYmFja2VuZDo4MDgwL2hlYWx0aDsKICAgICAgICB9CgogICAgICAgICMgU1BBIGZhbGxiYWNrCiAgICAgICAgbG9jYXRpb24gLyB7CiAgICAgICAgICAgIHRyeV9maWxlcyAkdXJpICR1cmkvIC9pbmRleC5odG1sOwogICAgICAgIH0KICAgIH0KfQo="    "${INSTALL_DIR}/nginx/nginx.conf"

# docker-compose.yml
cat > "${INSTALL_DIR}/docker-compose.yml" << 'DCEOF'
version: "3.9"

networks:
  eclipse_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  xray:
    image: teddysun/xray:latest
    container_name: eclipse_xray
    restart: unless-stopped
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    security_opt: [no-new-privileges:true]
    ports:
      - "443:443/tcp"
      - "8443:8443/tcp"
    volumes:
      - ./xray_config:/etc/xray
      - ./xray_logs:/var/log/xray
    networks:
      eclipse_net:
        ipv4_address: 172.20.0.2
    environment:
      - XRAY_LOCATION_CONFIG=/etc/xray
    ulimits:
      nofile: {soft: 65536, hard: 65536}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eclipse_backend
    restart: unless-stopped
    depends_on: [xray]
    ports:
      - "8080:8080"
    volumes:
      - ./xray_config:/etc/xray
      - ./xray_logs:/var/log/xray
      - ./data:/app/data
    networks:
      eclipse_net:
        ipv4_address: 172.20.0.3
    environment:
      - ECLIPSE_PASSWORD=${ECLIPSE_PASSWORD}
      - XRAY_CONFIG_PATH=/etc/xray/config.json
      - XRAY_LOG_PATH=/var/log/xray
      - SERVER_IP=${SERVER_IP}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - DATA_PATH=/app/data
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: eclipse_nginx
    restart: unless-stopped
    depends_on: [backend]
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      eclipse_net:
        ipv4_address: 172.20.0.4
DCEOF
ok "Создан: ${INSTALL_DIR}/docker-compose.yml"

# requirements.txt
cat > "${INSTALL_DIR}/backend/requirements.txt" << 'REQEOF'
fastapi==0.111.0
uvicorn[standard]==0.30.1
httpx==0.27.0
qrcode[pil]==7.4.2
apscheduler==3.10.4
psutil==5.9.8
Pillow==10.3.0
pydantic==2.7.1
REQEOF
ok "Создан: backend/requirements.txt"

# Dockerfile
cat > "${INSTALL_DIR}/backend/Dockerfile" << 'DKEOF'
FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends curl gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
RUN mkdir -p /app/data /etc/xray /var/log/xray && chmod 777 /app/data /etc/xray /var/log/xray
EXPOSE 8080
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
DKEOF
ok "Создан: backend/Dockerfile"

cat > "${INSTALL_DIR}/xray_config/config.json" << 'XCFG'
{"log":{"loglevel":"warning"},"inbounds":[],"outbounds":[{"protocol":"freedom"}]}
XCFG
ok "Создан: xray_config/config.json"

# ══════════════════════════════════════════════════════════════════════
step "СОЗДАНИЕ .env"

cat > "${INSTALL_DIR}/.env" << ENVEOF
ECLIPSE_PASSWORD=${ECLIPSE_UI_PASS}
SERVER_IP=${SERVER_IP}
PRIVATE_KEY=${PRIVATE_KEY}
PUBLIC_KEY=${PUBLIC_KEY}
ENVEOF
chmod 600 "${INSTALL_DIR}/.env"
ok ".env создан: ${INSTALL_DIR}/.env  (права 600)"

chmod 777 "${INSTALL_DIR}/data"
chmod 777 "${INSTALL_DIR}/xray_config"
chmod 777 "${INSTALL_DIR}/xray_logs"
ok "Права на data/xray_config/xray_logs: OK"

# ══════════════════════════════════════════════════════════════════════
step "ЗАПУСК DOCKER СТЕКА"

cd "${INSTALL_DIR}"
docker compose down --remove-orphans >>$LOG 2>&1 || true

run_spin "Pull: teddysun/xray"     docker pull teddysun/xray:latest
run_spin "Pull: nginx:alpine"      docker pull nginx:alpine
run_spin "Pull: python:3.12-slim"  docker pull python:3.12-slim
run_spin "Build: backend"          docker compose --env-file .env build --no-cache

inf "Запуск контейнеров…"
docker compose --env-file .env up -d >>$LOG 2>&1   || { tail -30 "$LOG" | sed 's/^/    /'; die "docker compose up завершился с ошибкой"; }
ok "Контейнеры запущены"

# ══════════════════════════════════════════════════════════════════════
step "ПРОВЕРКА ЗАПУСКА (до 90 секунд)"

echo ""
ALL_OK=false
for attempt in $(seq 1 18); do
  sleep 5
  SECS=$((attempt*5))

  ST_X=$(docker inspect --format='{{.State.Status}}' eclipse_xray    2>/dev/null || echo "—")
  ST_B=$(docker inspect --format='{{.State.Status}}' eclipse_backend 2>/dev/null || echo "—")
  ST_N=$(docker inspect --format='{{.State.Status}}' eclipse_nginx   2>/dev/null || echo "—")

  H_API=$(curl -s -o /dev/null -w "%{http_code}" --max-time 3 http://127.0.0.1:8080/health 2>/dev/null || echo "—")
  H_WEB=$(curl -s -o /dev/null -w "%{http_code}" --max-time 3 http://127.0.0.1/           2>/dev/null || echo "—")

  xi="${ST_X}"; [[ "$ST_X" == "running" ]] && xi="${G}✔${NC}"
  bi="${ST_B}"; [[ "$ST_B" == "running" ]] && bi="${G}✔${NC}"
  ni="${ST_N}"; [[ "$ST_N" == "running" ]] && ni="${G}✔${NC}"
  ai="${H_API}"; [[ "$H_API" == "200" ]] && ai="${G}200✔${NC}"
  wi="${H_WEB}"; [[ "$H_WEB" == "200" ]] && wi="${G}200✔${NC}"

  printf "  ${DIM}[%3ds]${NC}  xray=%-12b  backend=%-12b  nginx=%-12b  api=%-10b  web=%b\n"     "$SECS" "$xi" "$bi" "$ni" "$ai" "$wi"

  if [[ "$ST_X" == "running" && "$ST_B" == "running" && "$ST_N" == "running"      && "$H_API" == "200" && "$H_WEB" == "200" ]]; then
    ALL_OK=true; break
  fi
done

echo ""
for lc in "Xray-core:eclipse_xray" "Backend:eclipse_backend" "Nginx:eclipse_nginx"; do
  label="${lc%%:*}"; cont="${lc##*:}"
  st=$(docker inspect --format='{{.State.Status}}' "$cont" 2>/dev/null || echo "не найден")
  if [[ "$st" == "running" ]]; then
    ok "${label}: ${G}${B}RUNNING${NC}"
  else
    warn "${label}: ${R}${B}${st}${NC}"
    docker logs --tail 20 "$cont" 2>&1 | sed 's/^/      /' || true
  fi
done

FA=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 http://127.0.0.1:8080/health 2>/dev/null || echo "—")
FW=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 http://127.0.0.1/           2>/dev/null || echo "—")
[[ "$FA" == "200" ]] && ok "API /health: ${G}${B}HTTP 200 ✔${NC}" || warn "API: HTTP ${FA}"
[[ "$FW" == "200" ]] && ok "Веб-интерфейс: ${G}${B}HTTP 200 ✔${NC}" || warn "Веб: HTTP ${FW}"

# ══════════════════════════════════════════════════════════════════════
echo ""
if $ALL_OK; then
  echo -e "${G}${B}╔════════════════════════════════════════════════════════╗${NC}"
  echo -e "${G}${B}║        ✅  ECLIPSE VPN УСПЕШНО УСТАНОВЛЕН!             ║${NC}"
  echo -e "${G}${B}╚════════════════════════════════════════════════════════╝${NC}"
else
  echo -e "${Y}${B}╔════════════════════════════════════════════════════════╗${NC}"
  echo -e "${Y}${B}║    ⚠  УСТАНОВКА ЗАВЕРШЕНА — ПРОВЕРЬТЕ ПРЕДУПРЕЖДЕНИЯ  ║${NC}"
  echo -e "${Y}${B}╚════════════════════════════════════════════════════════╝${NC}"
fi

echo ""
echo -e "${Y}${B}  ┌────────────────────────────────────────────────────┐${NC}"
echo -e "${Y}${B}  │           КАК ЗАЙТИ В ВЕБ-ИНТЕРФЕЙС               │${NC}"
echo -e "${Y}${B}  └────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  Открой в браузере:"
echo ""
echo -e "  ${B}${C}     ➜  http://${SERVER_IP}/${NC}"
echo ""
echo -e "  Логин:   ${B}eclipse${NC}"
echo -e "  Пароль:  ${B}[введённый при установке]${NC}"
echo ""
echo -e "${B}  ┌────────────────────────────────────────────────────┐${NC}"
echo -e "${B}  │              ПАРАМЕТРЫ VPN                         │${NC}"
echo -e "${B}  └────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  Сервер:    ${C}${SERVER_IP}${NC}"
echo -e "  TCP  443:  ${C}VLESS + Reality  (xtls-rprx-vision)${NC}"
echo -e "  gRPC 8443: ${C}VLESS + Reality  (multiPath)${NC}"
echo -e "  PublicKey: ${C}${PUBLIC_KEY}${NC}"
echo ""
echo -e "  ${DIM}QR-коды и VLESS-ссылки → в веб-интерфейсе${NC}"
echo ""
echo -e "${B}  ┌────────────────────────────────────────────────────┐${NC}"
echo -e "${B}  │                 УПРАВЛЕНИЕ                         │${NC}"
echo -e "${B}  └────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${C}cd ${INSTALL_DIR}${NC}"
echo -e "  Статус:     ${C}docker compose ps${NC}"
echo -e "  Логи:       ${C}docker compose logs -f${NC}"
echo -e "  Перезапуск: ${C}docker compose restart${NC}"
echo -e "  Остановить: ${C}docker compose down${NC}"
echo ""
echo -e "  .env:          ${C}cat ${INSTALL_DIR}/.env${NC}"
echo -e "  Лог установки: ${C}cat ${LOG}${NC}"
echo ""

if [[ ${#ERRORS[@]} -gt 0 ]]; then
  echo -e "${Y}${B}  Предупреждения:${NC}"
  for e in "${ERRORS[@]}"; do echo -e "  ${Y}•${NC} ${e}"; done
  echo ""
fi

echo -e "${G}${B}════════════════════════════════════════════════════════${NC}"
echo ""
